### ISSUE TITLE
PVS Studio static analyser reports some issues

### ISSUE THREAD

**Issue by pavel-pimenov** [ValveSoftware/GameNetworkingSockets#10]
Report:
http://www.fly-server.ru/pvs-studio/GameNetworkingSockets/

**Comment by tycho** [comment]
We've done a lot of cleanup, and the top offenders in that report don't exist anymore. Mind re-running it?

**Comment by pavel-pimenov** [comment]
ok. rebuild http://www.fly-server.ru/pvs-studio/GameNetworkingSockets/
hm... remove src/GameNetworkingSockets.sln

**Comment by tycho** [comment]
Looks like most of the warnings are noise now.

Yeah, the solution file was removed because it was generated by our internal build system (VPC). We're going to make it possible to generate a Visual Studio solution using either Meson or CMake soon -- or maybe both.

**Comment by nerzhul** [comment]
@tycho both should be nice, cmake is the minimum for many games :)
