### ISSUE TITLE
The implementation of `SteamNetworkingIPAddr` functionality is lost

### ISSUE THREAD

**Issue by nxrighthere** [ValveSoftware/GameNetworkingSockets#100]
Not sure when and how this happened, but the flat interface has only the [prototypes](https://github.com/ValveSoftware/GameNetworkingSockets/blob/master/include/steam/steamnetworkingsockets_flat.h#L104).

**Comment by nxrighthere** [comment]
Alright, it seems that everything works fine on my end now, I'm ready for the update.

**Comment by fletcherdvalve** [comment]
Thanks!  I'm gonna get some help fixing our continuous integration -- some odds and ends on some platforms are broken -- and then I'll make a release.

**Comment by nxrighthere** [comment]
Just [pushed it](https://github.com/nxrighthere/ValveSockets-CSharp/commit/d059a1f1680aabbca0888aa169bd3c37b14e0059) to the master.
