### ISSUE TITLE
Build-in clock synchonization

### ISSUE THREAD

**Issue by rjdgtn** [ValveSoftware/GameNetworkingSockets#101]
Is there a build-in clock synchronization between client and server like in RakNet and Photon?

**Comment by fletcherdvalve** [comment]
Nope, and this feature is not currently on the roadmap.

**Comment by yamashi** [comment]
@rjdgtn I wrote an implementation for that on top of this lib if you want to take a look 

https://github.com/tiltedphoques/TiltedConnect/blob/master/Code/connect/src/SynchronizedClock.cpp

**Comment by rjdgtn** [comment]
Thx, i will

**Comment by fletcherdvalve** [comment]
I'm going to go ahead and close this, as I think it's outside of what we want to do with this project.
