### ISSUE TITLE
SteamAPI_SteamNetworkingIPAddr_ParseString failes on msvc

### ISSUE THREAD

**Issue by ChristofferZordix** [ValveSoftware/GameNetworkingSockets#107]
Hello,
I am building this library on visual studio and I noticed that SteamNetworkingIPAddr::ParseString failed to parse "192.168.30.0". On further inspection revealed that sscanf behaves differently on msvc. 

In the function SteamAPI_SteamNetworkingIPAddr_ParseString. sscanf is run and returns 4. It parses n1, n2, n3, n4 correctly but garbage is in n5. So msvc seems to touch n5 even if it returns 4 to nRes.

So it seems like msvc version of sscanf might be broken? I have not checked any other places where you use the sscanf function but it seems like there could be more problem areas?

**Comment by fletcherdvalve** [comment]
What version of MSVC are you using?  I've never seen that before, and cannot reproduce it in VS 2017.  But I don't doubt you, and I will fix the code to not rely on this assumption.

**Comment by fletcherdvalve** [comment]
OK, I am really interested in what compiler and CRT libs you are using.  Because this is not the only place I have written code like this in my career, so it is news to me that any implementation of scanf would touch values that it did not successfully parse.

Regardless, I submitted a fix, because it's probably bad to rely on subtle behaviour of functions like this, and better to be more explicit.

**Comment by ChristofferZordix** [comment]
Hmm I do not know how to get that information.. I usually do not have to do that. But will give it a try.

I am building for 64bit.

I am using Visual Studio 2017 Version 15.9.21.
Windows SDK Version 10.0.17763.0
Platform Toolset: Visual Studio 2017 (v141)

Visual C++ 2017   00369-60000-00001-AA208
Microsoft Visual C++ 2017

cl.exe /?
Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27038 for x64

MSBuild /?
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework

Debug Source Files points to this directory:
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\

I see that we link with /MT. Might change that to /MD

**Comment by ChristofferZordix** [comment]
aaa. I see what is wrong now. We had a local change that has a virtual port and I somehow missed that we inititialized out variables like this:
`int n1, n2, n3, n4, n5, n6 = 0;`
So my n5 was garbage all along... False alarm!
Sorry for taking up your time

**Comment by ChristofferZordix** [comment]
Did a more focused test and initialized all vars to zero and all worked.. and then noticed that we had n6 =/

**Comment by fletcherdvalve** [comment]
Oh, thank goodness.  Thanks forinvestigating!
