### ISSUE TITLE
Connect through DNS ip (ex: myserver.com)

### ISSUE THREAD

**Issue by gtnardy** [ValveSoftware/GameNetworkingSockets#111]
Hello, dumb question, but how can I connect to my server with a DNS IP?

This is how I'm connecting currently with numeric IPs:

```
	SteamNetworkingIPAddr NetworkingIPAddr;
	NetworkingIPAddr.ParseString(IP.c_str())

	ListenSocket = NetworkingSockets->ConnectByIPAddress(NetworkingIPAddr, 0, nullptr);
```

**Comment by SleepyMode** [comment]
You'll generally need to get the IP address from the hostname. There are different ways to do it, I think `gethostbyname` could be cross-platform but I honestly wouldn't know.

**Comment by fletcherdvalve** [comment]
Yeah, there's no interface right now to connect by domain name.  Oddly, this isn't something that has come up before.  You'll need to resolve the name yourself first using the standard operating system mechanisms (e.g. `gethostbyname` as @SleepyMode mentioned)
