### ISSUE TITLE
Steam version crashes on shutdown, if shutdown soon after initialization

### ISSUE THREAD

**Issue by HiddenMonk** [ValveSoftware/GameNetworkingSockets#116]
I seem to be crashing if I close my steam game as steam tries to initialize the relay network. This happens when calling CheckPingDataUpToDate(1e10f) or GetLocalPingLocation and then closing the game, so I assume its something with the relay stuff, and not necessarily a specific method.
I have these methods called right at game start, so if I close the game right as it opens, it crashes. Waiting a bit and then closing the game avoids the crash.

I am using the latest steam client and Steamworks sdk 1.48, using Steamworks .net for unity3d game engine. I had this issue even on an older steamworks sdk, probably ever since steamnetworkingsockets have been released.

**Comment by fletcherdvalve** [comment]
Do you have a stack trace or dump file you could send to me?

**Comment by HiddenMonk** [comment]
Is there somewhere I can send you it privately? I dont know what info these might have in it. Also, should I work on a small repro case?

**Comment by HiddenMonk** [comment]
Here is a steam key to the private game on steam, MeecheenMe, that you can cause the crash on.
Its currently using an older version of steamworks sdk, but the bug is probably the same.
2NTJ5-V9FMG-CA5CM

**Comment by fletcherdvalve** [comment]
You can email me at fletcherd [at] valvesoftware.com.

**Comment by HiddenMonk** [comment]
k, I sent.

**Comment by fletcherdvalve** [comment]
Two notes:
* This only affects the Steam version, not the opensource code.  (But it's fine to track it here.)
* This bug happens on app shutdown, if you shut down very quickly after initializing the libraries.

I understand the problem and hopefully will have a fix soon.

**Comment by HiddenMonk** [comment]
Sorry to bother, just wondering if there is any update on this. I still have the issue, even on a steam beta client.

**Comment by fletcherdvalve** [comment]
The steam client released today *should* fix this issue.  If you have a chance to try it out, I'd appreciate if you can confirm it fixes your issue.

https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/4042499938193651739

**Comment by HiddenMonk** [comment]
Everything seems to work fine now =)
I tested with the crash test build I made when making this thread, with my game on steam, and with a local version of my game, and when not using the steam beta client they would all crash when exiting too early. When I use the steam beta client, they all seem to close without a problem.
Thank you =), I will close the thread.
