### ISSUE TITLE
How to build steamwebrtc.dll？

### ISSUE THREAD

**Issue by leejet** [ValveSoftware/GameNetworkingSockets#121]
How to build steamwebrtc.dll？

**Comment by fletcherdvalve** [comment]
Hi @leejet .  I described what needed to be done in #117.  (Closing this as a duplicate.)

If they have not made significant changes to the google webrtc code, it might be pretty easy to get everything working.  If they have made big changes, we might be stuck until I can get around to updating our code to match.

**Comment by leejet** [comment]
Thanks a lot.
