### ISSUE TITLE
Class ISteamNetworkingSocketsCallbacks  is not defined in steamworks version

### ISSUE THREAD

**Issue by SnapperTT** [ValveSoftware/GameNetworkingSockets#124]
Problem: Any code using `ISteamNetworkingSocketsCallbacks` cannot be compiled against steamworks as the class is not defined in any of the header files (it is only forward declared). The class is defined in `steamnetworkingsockets.h` which is not present in the steamworks distribution.

Steamworks Version:
```
$ grep -rnw ISteamNetworkingSocketsCallbacks
sdk/public/steam/isteamnetworkingsockets.h:23:class ISteamNetworkingSocketsCallbacks;
sdk/public/steam/isteamnetworkingsockets.h:670:	virtual void RunCallbacks( ISteamNetworkingSocketsCallbacks *pCallbacks ) = 0;
```

Github Version:
```
$ grep -rnw ISteamNetworkingSocketsCallbacks
include/steam/isteamnetworkingsockets.h:23:class ISteamNetworkingSocketsCallbacks;
include/steam/isteamnetworkingsockets.h:449:	virtual void RunCallbacks( ISteamNetworkingSocketsCallbacks *pCallbacks ) = 0;
include/steam/steamnetworkingsockets.h:36:class ISteamNetworkingSocketsCallbacks
include/steam/steamnetworkingsockets.h:39:	inline ISteamNetworkingSocketsCallbacks() {}
include/steam/steamnetworkingsockets.h:42:	inline ~ISteamNetworkingSocketsCallbacks() {}
tests/test_connection.cpp:271:struct TestSteamNetworkingSocketsCallbacks : public ISteamNetworkingSocketsCallbacks
src/steamnetworkingsockets/clientlib/csteamnetworkingsockets.h:111:	virtual void RunCallbacks( ISteamNetworkingSocketsCallbacks *pCallbacks ) override;
src/steamnetworkingsockets/clientlib/csteamnetworkingsockets.cpp:995:void CSteamNetworkingSockets::RunCallbacks( ISteamNetworkingSocketsCallbacks *pCallbacks )
src/steamnetworkingsockets/clientlib/steamnetworkingsockets_flat.cpp:183:	struct CallbackAdapter : ISteamNetworkingSocketsCallbacks
examples/example_chat.cpp:230:class ChatServer : private ISteamNetworkingSocketsCallbacks
examples/example_chat.cpp:542:class ChatClient : private ISteamNetworkingSocketsCallbacks
```

Steamworks version 1.49, SteamGameNetworkingSockets version 1.1.0

**Comment by SnapperTT** [comment]
Likewise the functions `SteamDatagramClient_Init`, `SteamDatagramClient_SetAppID` and `SteamDatagramClient_Kill` are not defined in any header file.

**Comment by fletcherdvalve** [comment]
I think this is basically a dup of issue #93.  Right now the two interfaces are not identical, around initialization and pumping the callbacks.  I'm not sure that it is valuable to unify this, or really a design goal.  If you link with Steamworks, initialization and pumping callbacks will happen through Steam, just like all of the other Steamworks interfaces.  If you are using the standalone lib, it will be differently.  I think this just needs to be handled by a #define or something in the code.  I don't think there is value in unifying these right now.

**Comment by fletcherdvalve** [comment]
I changed how callbacks are plumbed through, so this is now fixed!
