### ISSUE TITLE
High bandwidth when ping is 0

### ISSUE THREAD

**Issue by yamashi** [ValveSoftware/GameNetworkingSockets#126]
Hello,

I have observed that my application uses a lot more bandwidth when I am running both the server and clients on the same machine. Inducing some network lag fixes the issue. I believe the RTT calculation might end up being equal to 0 thus retrying to send the packets immediately because it still has not processed an ACK. A workaround would be to have a min value for the RTT to prevent this behavior.

EDIT: Looking at the code I can see there is a function that handles ping < 1 and returns 500, maybe 1 is still too high ?

**Comment by fletcherdvalve** [comment]
Hio!  Can you describe in a bit more detail what you are doing to reproduce this issue?

**Comment by fletcherdvalve** [comment]
Gonna close this issue.  Feel free to reopen if you have any more info.
