### ISSUE TITLE
Need to refresh certs for long-running processes such as dedicated servers

### ISSUE THREAD

**Issue by andererandre** [ValveSoftware/GameNetworkingSockets#129]
48 hours after server startup clients are unable to connect. The server log simply states that the client disconnected:

```
[SteamNet_Msg] [#xxx UDP steamid:xxx@xxx:xxx] closed by peer
```

On the client we're getting much more info, which basically states that the cert expired:

```
[SteamNet_Msg] RelayNetWorkStatus:  avail=Attempting  config=Attempting  anyrelay=Not Attempted   (Attempt #1 to fetch config from xxx)
[SteamNet_Verbose] Requesting cert for [U:1:xxx] from Steam
[SteamNet_Msg] AuthStatus (steamid:xxx):  Attempting  (Requesting cert)
[SteamNet_Verbose] Got cert for steamid:xxx from Steam
[SteamNet_Msg] [#xxx UDP invalid@xxx:xxx] problem detected locally (4003): Bad cert: Cert expired xxx seconds ago
[SteamNet_Msg] [ConnectOK] Ignored bad #xxx UDP invalid@xxx:xxx.  Failed crypto init.  Bad cert: Cert expired xxx seconds ago
[SteamNet_Warning] SDR network config fetch first attempt failed.  HTTP 504.  .  Trying again.
[SteamNet_Msg] Got SDR network config.  Loaded revision 281 OK
[SteamNet_Msg] RelayNetWorkStatus:  avail=Not Attempted  config=OK  anyrelay=Not Attempted   ()
[SteamNet_Msg] AuthStatus (steamid:xxx):  OK  (OK)
```

We naturally assumed it must be something we're doing wrong, but we're not seeing an immediate way to do a cert refresh in the API. We also found a few reports from Dota 2 and CSGO, which make us think it might not be entirely our fault:

- https://dev.dota2.com/forum/bugs/performance-technical-support/271473-the-daily-unable-to-connect-problem?t=290094
- https://www.reddit.com/r/DotA2/comments/cpe0kb/failed_to_connect_to_reason_code_4003_bad_cert/
- https://steamcommunity.com/app/730/discussions/0/1629664606984521594/

**Comment by fletcherdvalve** [comment]
What app is this, and exactly what code are you running?  I am assuming that this is Steamworks SDK, not the opensource code.  This has been fixed, although I don't know if it's in the code you have.

**Comment by fletcherdvalve** [comment]
A fix for this is in the works.

**Comment by fletcherdvalve** [comment]
Did not intend to close this, just wanted to mention it.  I'll close it when the fix actually ships in Steam

**Comment by fletcherdvalve** [comment]
@andererandre The steam beta client released today has code to renew the certs.  If you have a chance to try it out, would you let me know if it is working for you?

https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/4042499938193651739

**Comment by andererandre** [comment]
I can confirm the issue is fixed in the beta.
