### ISSUE TITLE
[vcpkg] Port not generating DLL file 

### ISSUE THREAD

**Issue by valenotary** [ValveSoftware/GameNetworkingSockets#131]
Following the BUILDING.md file for installing the library through vcpkg. I can see in the directories (of vcpkg) that it builds the .libs and places the headers in the correct include directories, but there is no DLL file that is generated in the bin directory of vcpkg.  I'm not sure if this is unintentional/intentional, but the majority of other vcpkg ports generate DLLs so I assumed this might be the former. 
Also, this is from a user that integrates vcpkg as a part of Visual Studio projects.

**Comment by aiusepsi** [comment]
Hi, thanks for kicking the tires on the vcpkg port. Definitely unintentional. I've put in a PR which should sort it.
