### ISSUE TITLE
[vcpkg] DLL only builds with [libsodium] as backend

### ISSUE THREAD

**Issue by valenotary** [ValveSoftware/GameNetworkingSockets#135]
Hello, 

Been really adamant on trying to get the vcpkg port to work for me : )
Surprisingly though, I just randomly tried including [libsodium] as the crypto backend (not expecting anything to change), but the DLL built with that! I got the example_chat program to work because of this. 

To reconfirm this, I:
1) Uninstalled the gamenetworkingsockets[core,libsodium] port 
2) Tried installing just gamenetworkingsockets[core]
3) I looked into the vcpkg/installed/triplet/bin directory, and no DLL was generated when installing the [core] version 
4) Uninstalled [core], and reinstalled with the [libsodium] backend 
5) Again, it generated the DLL !

Very weird! Not sure if this is just me or if it happens to anyone else. Just pointing out my experience with the vcpkg port.

**Comment by fletcherdvalve** [comment]
I will wait and see if @aiusepsi has a chance to look into this, since he understands the vcpkg stuff.

**Comment by aiusepsi** [comment]
That's peculiar; the DLL being made isn't conditional on the crypto backend in use. I'll do a check on my end with a fresh vcpkg install & fresh GNS clone to be sure. My first thought is that perhaps vcpkg is caching some state for the core build (from your previous attempts to build it) and that's causing the issue, but I do recall that you said you'd cleared out vcpkg previously, which makes it a bit odd.

**Comment by aiusepsi** [comment]
The check on my end didn't turn up anything, DLL was built as expected with the default feature set.

One thing to possibly try is to update the version in the vcpkg [CONTROL](https://github.com/ValveSoftware/GameNetworkingSockets/blob/master/vcpkg_ports/gamenetworkingsockets/CONTROL) file to a different value in your clone; this might prompt vcpkg to clear cache, if that is the problem.

**Comment by fletcherdvalve** [comment]
I'm not able to reproduce this, either.
