### ISSUE TITLE
WSAEWOULDBLOCK instead of EWOULDBLOCK 

### ISSUE THREAD

**Issue by LeventSevgili** [ValveSoftware/GameNetworkingSockets#144]
I think below if check is okay for POSIX but seems quite not right when using winsock2 (when _WIN32 is defined). I was having "Failed to recv from trivial signaling server" error on client side when i was trying to connect to the signal server. I replaced EWOULDBLOCK with WSAEWOULDBLOCK, now connection to signal server seems stable. (it was disconnecting immediately after connect.)

Maybe better to separate this check per platform. Thanks.

https://github.com/ValveSoftware/GameNetworkingSockets/blob/34ead6c9e2fede28897497590f0cde53986b4f80/examples/trivial_signaling_client.cpp#L225

**Comment by LeventSevgili** [comment]
Well, it is a bit different, on my setup; vs2019 + windows 10, the winsock2 returns WSAEWOULDBLOCK when there is nothing to grab from buffer instead of EWOULDBLOCK for a non blocking thread. When i replaced EWOULDBLOCK with WSAEWOULDBLOCK, it started to work correctly for me.

**Comment by fletcherdvalve** [comment]
Oh I see yes, two separate issues.  My mistake.

**Comment by fletcherdvalve** [comment]
Fixed in 515a34e3ccad256df5527101c125b073df82cf11
