### ISSUE TITLE
"trivial_signaling_client" class nonblocking socket implementation

### ISSUE THREAD

**Issue by LeventSevgili** [ValveSoftware/GameNetworkingSockets#145]
Thanks for the implementation of p2p and all related classes. Perfect progress, congratulations.

I just tested it all works okay, great.

When i run the go signal server on my pc and run the server and client app, it worked quite nice, they are connected via signal server.

Problem started to arise when i installed the server app to my laptop which is connected to the same router, network, and run it. 
I just wanted to test to connect this server app to the signal server (which is at my pc) and see if it can connect.
It gives that error "Failed to send %d bytes to trivial signaling server.  send() returned %d, errno=%d.  Closing and restarting connection."

Then i dig in, and figured it out that, as long as it is non-blocking socket, the send method is sent when the connect is not yet established and it is assumed that it will be buffered so when connection appears, "Greeting" will be send accordingly. But it did not work for me while i try to connect with my laptop because of some delay i guess. The send method return error value of WSAENOTCONN, which means not connected, and socket is closed to be reconnecting again and something crashes the app there.

My Pc and laptop has windows 10 OS. I built the GNS with VS 2019 latest with CMake.

What i did was, i did not make the socket nonblocking till connect, then i immediately make it non-blocking with "ioctlsocket", in other words, i changed the order of calling "connect" and "ioctlsocket". It started to work nice.
Well it blocks till connect which is not preferred, maybe it is better to wait till connection is established with select with non blocking, and then call the send method, just fyi. Thanks.

Thank you very much!

**Comment by fletcherdvalve** [comment]
Thanks for testing this!

Yeah, I noticed it was flaky but didn't dig into it - I'm glad you found the underlying cause.

Given that signals are allowed to drop, another idea would be to just ignore that particular failure code.

**Comment by fletcherdvalve** [comment]
Fixed in 515a34e3ccad256df5527101c125b073df82cf11
