### ISSUE TITLE
p2ptransport_channel.cc --- calling from different thread causes assert

### ISSUE THREAD

**Issue by anchor76** [ValveSoftware/GameNetworkingSockets#150]
hello,

i got `RTC_DCHECK_RUN_ON(network_thread_);` assert again within webrtc.
attached screenshots.
shot1: [https://ibb.co/MNPsWdk](https://ibb.co/BLCgHL4)
shot2: [https://ibb.co/BLCgHL4](https://ibb.co/BLCgHL4)

request:
i would like to ask a `SetIdentity(const SteamNetworkingIdentity& pIdentity)` function into the peer interface.

**Comment by fletcherdvalve** [comment]
Haven't had a chance to investigate this, but hoping to do so next week.

**Comment by anchor76** [comment]
hello @fletcherdvalve , i just pinged this issue :) please check it when you have time ... thanks.

**Comment by anchor76** [comment]
hello @fletcherdvalve , i just pinged this issue :) please check it when you have time ... thanks.

**Comment by fletcherdvalve** [comment]
Hoooooping to get to it this week.  Sorry!  Got a lot going on.

**Comment by anchor76** [comment]
is the development of this net-lib suspended? :/

**Comment by anchor76** [comment]
so good, i see project activity :) @fletcherdvalve when can you check this issue?

**Comment by fletcherdvalve** [comment]
I'm still working on this project!  I just haven't had time to dig into this issue, I'm sorry.

**Comment by anchor76** [comment]
it's okay @fletcherdvalve , thanks for your response. when can you check this issue?

**Comment by fletcherdvalve** [comment]
HELLO!  I'm finally looking at this.  One thing that bothers me is that I'm not able to reproduce this on linux, which is where I do most of my dev.  I can see the problem from your stack trace, it's very straightforward, but I'm not sure how many other instances of the same basic problem are going to happen, so I'd like to be able to reproduce it.
