### ISSUE TITLE
Recurrence of openssl issue

### ISSUE THREAD

**Issue by SDGNelson** [ValveSoftware/GameNetworkingSockets#152]
This is a continuation of #148 

A few hosts have been experimenting with GNS again, but unfortunately one has received a report of same issue today. The debug message was: "Bad cert: CA key 18220590129359924542 is not known to us"

The player is using a Windows laptop with the latest public release of Steam. The "file version" of their steamclient64.dll was 6.16.34.46

Once they set the environment variable "OPENSSL_ia32cap=:~0x20000000" they were able to join the server.

Is it possible that the Steam openssl lib regressed again with the October 23rd update?

**Comment by fletcherdvalve** [comment]
Welp.

From what I can tell, that version of steamclient64.dll should have the openssl fix.  I'll see if I can do some digging.

**Comment by fletcherdvalve** [comment]
Alright, after more digging, I have determined that the 64-bit version has a SNAFU unique to that platform.  We'll get this fixed immediately.  Blaaaarg, sorry.

**Comment by SDGNelson** [comment]
Whoops! Thanks for digging into it.

For what it's worth: there has been a lot of positive feedback from players saying GNS works better for them than the old SteamNetworking did, so it will be exciting once these last few straggling issues are resolved.

**Comment by fletcherdvalve** [comment]
Also, I think the 32-bit build is actually still broken, too.  We just totally screwed up with the last "fix".

**Comment by fletcherdvalve** [comment]
OK, for reals, this should be fixed now in the latest steam beta client.....

https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/2926737384498359989

**Comment by SDGNelson** [comment]
Thanks for the update! I think server hosts will wait until the fix is merged into the next public Steam release before re-enabling GNS, so it might be a bit before we hear from them.

**Comment by fletcherdvalve** [comment]
Beta has been promoted to the public client, so anybody who has this issue should be able to update, and it *should* be fully resolved.

https://store.steampowered.com/news/77340/
