### ISSUE TITLE
Is it possible not to use a global callback (SetGlobalCallback_SteamNetConnectionStatusChanged) setting for p2p? like in the example_chat.

### ISSUE THREAD

**Issue by LeventSevgili** [ValveSoftware/GameNetworkingSockets#153]
Hey,

Just wondering is it possible to use below code for P2P initialization like in the non-p2p version, like in the example_chat by giving option for creating the listen socket?

```
SteamNetworkingConfigValue_t opt;
opt.SetPtr(k_ESteamNetworkingConfig_Callback_ConnectionStatusChanged, (void*)SteamNetConnectionStatusChangedCallback);
m_pInterface->CreateListenSocketP2P(g_nVirtualPortLocal, 0, &opt); // last argument (&opt) is nullptr in the test_p2p project
```

I tested to use the above for the p2p initialization, it compiled but did not work, no callback is retrieved.

So why do i need it?
I'm trying a masterclient model, so a server and a client is at the same process. Normally it works very well without p2p by following the _example_chat_ initialization pattern of GNS.

But in the _test_p2p_ project, _SetGlobalCallback_SteamNetConnectionStatusChanged_ is used instead of setting a config. So it seems like callbacks are retrieved **only** by the last registerer. 

Is it a must for p2p initialization to use the GlobalCallback or the config usage can be used? Thank you very much!

**Comment by fletcherdvalve** [comment]
The way this *should* work is that a callback (or any option, really) set on the listen socket (inherited by the connections received through that listen socket) will take priority over the global option.  The order that they are registered should not matter.

But remember that callbacks set on a listen socket will not be in effect for any outbound connections initiated locally.

I am still hoping to be able to investigate the WevRTC ICE bugs soon!

**Comment by LeventSevgili** [comment]
Yes, taking priority over the global option would be perfect!

**Comment by fletcherdvalve** [comment]
OK, well, that is supposed to be the way all options work.  All connection options are inherited, *dynamically*.  Global -> Per-interface -> listen socket (if any) -> connection.

Some options can only be set globally, since they are not per-connection, e.g. UDP packet loss simulation.

Let me know if you find that it doesn't behave that way.

**Comment by LeventSevgili** [comment]
Okay i see, here is my test:

I commented out the below line from test_p2p project.

`//SteamNetworkingUtils()->SetGlobalCallback_SteamNetConnectionStatusChanged( OnSteamNetConnectionStatusChanged );
g_hListenSock = SteamNetworkingSockets()->CreateListenSocketP2P( g_nVirtualPortLocal, 0, nullptr);
`

and replaced it with the below code instead. Because _CreateListenSocketP2P_ method has options argument that i can pass i guess.

```
SteamNetworkingConfigValue_t opt;
opt.SetPtr(k_ESteamNetworkingConfig_Callback_ConnectionStatusChanged, (void*)OnSteamNetConnectionStatusChanged);
g_hListenSock = SteamNetworkingSockets()->CreateListenSocketP2P( g_nVirtualPortLocal, 0, &opt );
```
In that way no callback i can get. I think it is not valid to pass _k_ESteamNetworkingConfig_Callback_ConnectionStatusChanged_ option to CreateListenSocketP2P maybe.

"I am still hoping to be able to investigate the WebRTC ICE bugs soon!" By the way, we tested on Android and iOS WebRTC GNS build and tests were quite super nice. With my firend we managed to connect two actual devices with GSM LTE On Off (different gsm operators), Wifi On Off (on different routers) all combinations, we were able to connect devices successfully, worked perfectly! Just FYI.

**Comment by fletcherdvalve** [comment]
I think this 0 as the 2nd positional argument here is a bug.  It's supposed to be the number of options, and the pointer is to an array.

```g_hListenSock = SteamNetworkingSockets()->CreateListenSocketP2P( g_nVirtualPortLocal, 0, &opt );```

That's great news about Android!

**Comment by LeventSevgili** [comment]
Ahh *facepalm. 
Sorry, I fixed it, it is working now! Took your time, sorry, Closing it.

**Comment by fletcherdvalve** [comment]
No problem, thanks for using and testing!
