### ISSUE TITLE
Cert expiry issue

### ISSUE THREAD

**Issue by PandahutMiku** [ValveSoftware/GameNetworkingSockets#154]
It seems certificates are still expiring and making all new clients unable to join.
We're running servers for the game unturned, who you probably know has recently switched to Game Networking Sockets.
The actual error is just
```
[2020-11-06 23:32:03] Client connection problem detected locally (4003) "Bad cert: Cert expired 6067 seconds ago"
[2020-11-06 23:32:03] Client transport failure: Unable to trust host encryption certificate.
```
It seems pretty random/odd though, we run 20 servers and restart them all every day at 9 AM GMT. This issue has happened once in the past 3 days to one specific server which was about 10 hours and then hit this issue. Nothing was abnormal about it, restarting the server fixed the issue, and the only info about it was in the client's log for failing to connect.

I was thinking it could be server time coming out of sync/drifting, but we monitor this, and this is sadly not the case. Our server's timezones are all set to UTC. (My own computer's time is not out of sync either, and this happened to 4+ people at once where they were suddenly unable to join with this error)
![image](https://user-images.githubusercontent.com/17209937/98432452-6d86e780-208c-11eb-963d-55f810f9d8a7.png)

Sorry for being vague/being unable to provide steps for replication. Kind of hoping it's something like the OpenSSL issue where it's an easy obvious fix. This happened to quite a few of our servers back ~2 weeks ago, but we assumed it was related to the OpenSSL issues and it didn't crop back up until the third day of running Game Networking Sockets again. If there's anything else I can do to help get this fixed, please let me know.

**Comment by SDGNelson** [comment]
Chiming in to add that this does seem to be a relatively common issue, as quite a few hosts are reporting sporadic problems with certificate renewal. The average Unturned server setup restarts once every 24 hours.

**Comment by fletcherdvalve** [comment]
It's not related to OpenSSL.  It looks like this is basically the same as issue #129, which another says has been fixed for them.

Can you confirm what version of steamclient.so / .dll you are using?  (I'm guessing that for your dedicated server, you package a specific .dll with your server.  Unless you are taking actions to keep it up to date, it might be out of date.  It's totally possible that the one we ship with the steamworks SDK is not up-to-date.

On the server logs, if you have hooked the output function, you should see some activity when the server attempts to renew the cert.  If you don't see any log output, or you see failure, that would be a clue.  Also when you get a cert, the log output should say how much longer the cert has until expiry.

**Comment by SDGNelson** [comment]
The dedicated server is using the Steam dedicated server redist depots, not packaging a specific .dll. It appears the current steamclient64.dll file version there is 5.91.61.88.

For this Friday's update I have added an option to change the GNS output detail level to hopefully get some more information about this issue.

**Comment by fletcherdvalve** [comment]
OK, that depot is out of date.  Let me ask around to make sure all I need to do is update it.  Also, it looks like we have a bad process here, as bugfixes are not getting rolled out in a timely manner.

**Comment by fletcherdvalve** [comment]
I have just updated that depot with binaries that match what are live in the public steam client.  Let me know if this fixes the issue.

Thanks for bringing this to my attention!

**Comment by SDGNelson** [comment]
Happy to say that there have been no further reports since the dedicated server depot was updated!
