### ISSUE TITLE
Library fails to compile on android arm64 and android x64 targets with vcpkg

### ISSUE THREAD

**Issue by WolfDan** [ValveSoftware/GameNetworkingSockets#155]
Hello! Thank you for the amazing library, I've been trying to compile the library for android arm64 and x64 without success, **so far just adding this to the cmake file** makes android compilation works without issue with vcpgk (x86 and arm)

`./CMakeList.txt` at `line 171` add

```cmake
	elseif(CMAKE_SYSTEM_NAME MATCHES Android)
		target_compile_definitions(${TGT} PUBLIC POSIX ANDROID)
```

and 

`./CMakeList.txt` at `line 259` add

```cmake
	elseif(CMAKE_SYSTEM_NAME MATCHES Android)
```

That's all to make android work, but when I want to compile it to `arm64` or `x64` I got this issue 

```
FAILED: src/CMakeFiles/GameNetworkingSockets.dir/tier1/netadr.cpp.o 
C:\Users\dragu\Android\android-ndk-r21d\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=aarch64-none-linux-android21 --gcc-toolchain=C:/Users/dragu/Android/android-ndk-r21d/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=C:/Users/dragu/Android/android-ndk-r21d/toolchains/llvm/prebuilt/windows-x86_64/sysroot -DANDROID -DCRYPTO_DISABLE_ENCRYPT_WITH_PASSWORD -DENABLE_OPENSSLCONNECTION -DGOOGLE_PROTOBUF_NO_RTTI -DGameNetworkingSockets_EXPORTS -DPOSIX -DSTEAMNETWORKINGSOCKETS_CRYPTO_25519_OPENSSL -DSTEAMNETWORKINGSOCKETS_CRYPTO_VALVEOPENSSL -DSTEAMNETWORKINGSOCKETS_FOREXPORT -DVALVE_CRYPTO_ENABLE_25519 -IC:/Users/dragu/Documents/GameNetworkingSockets/src/../include -IC:/Users/dragu/Documents/GameNetworkingSockets/src/common -IC:/Users/dragu/Documents/GameNetworkingSockets/src/public -Isrc -isystem C:/Users/dragu/Documents/vcpkg/installed/arm64-android/include -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -frtti -fexceptions  -fPIC   -O0 -fno-limit-debug-info    -fPIC -ffunction-sections -fdata-sections -fstack-protector-strong -fvisibility=hidden -fno-strict-aliasing -Wall -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-local-typedef -Wno-unused-const-variable -Wno-nested-anon-types -fvisibility-inlines-hidden -Wno-reorder -Wno-non-virtual-dtor -Wno-zero-as-null-pointer-constant -fno-exceptions -fno-rtti -pthread -std=gnu++11 -MD -MT src/CMakeFiles/GameNetworkingSockets.dir/tier1/netadr.cpp.o -MF src\CMakeFiles\GameNetworkingSockets.dir\tier1\netadr.cpp.o.d -o src/CMakeFiles/GameNetworkingSockets.dir/tier1/netadr.cpp.o -c C:/Users/dragu/Documents/GameNetworkingSockets/src/tier1/netadr.cpp
In file included from C:/Users/dragu/Documents/GameNetworkingSockets/src/tier1/netadr.cpp:10:
In file included from C:/Users/dragu/Documents/GameNetworkingSockets/src/public\tier1/netadr.h:8:
In file included from C:/Users/dragu/Documents/GameNetworkingSockets/src/public\tier0/basetypes.h:15:
In file included from C:/Users/dragu/Documents/GameNetworkingSockets/src/public\tier0/platform.h:31:
C:/Users/dragu/Documents/GameNetworkingSockets/src/public\minbase/minbase_endian.h:41:2: error: static_assert failed due to requirement 'sizeof(unsigned long) == sizeof(unsigned int)' "Compile time assert constraint is not true: sizeof( T ) == sizeof(uint32)"
        PLAT_COMPILE_TIME_ASSERT( sizeof( T ) == sizeof(uint32) );
        ^                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/Users/dragu/Documents/GameNetworkingSockets/src/public\minbase/minbase_macros.h:36:43: note: expanded from macro 'PLAT_COMPILE_TIME_ASSERT'
        #define PLAT_COMPILE_TIME_ASSERT( pred ) static_assert( pred, "Compile time assert constraint is not true: " #pred )
                                                 ^              ~~~~
C:/Users/dragu/Documents/GameNetworkingSockets/src/tier1/netadr.cpp:318:25: note: in instantiation of function template specialization 'DWordSwapC<unsigned long>' requested here
                        s->sin_addr.s_addr = BigDWord( INADDR_BROADCAST );
                                             ^
C:/Users/dragu/Documents/GameNetworkingSockets/src/public\minbase/minbase_endian.h:81:27: note: expanded from macro 'BigDWord'
        #define BigDWord( val )         DWordSwap( val )
                                        ^
C:/Users/dragu/Documents/GameNetworkingSockets/src/public\minbase/minbase_endian.h:73:19: note: expanded from macro 'DWordSwap'
#define DWordSwap DWordSwapC
                  ^
1 error generated.
```

So I research a bit and found that `BigDWord` was introduced for a switch compatibility change, reverting `BigDWord` to `htonl` and `BigWord` for `htons` **makes it compile without issue with android** `arm64` and `x64`

This issue is only with arm64 and x64, for arm and x86 the compilation works just fine 

Any idea on how to fix this without needing to replace `BigDWord` and `BigWord`?

Thank you

**Comment by aiusepsi** [comment]
Simplest fix is probably to cast `INADDR_BROADCAST` on line 318 of src/public/minbase/minbase_endian.h to uint32.

Root of the issue seems to be that INADDR_BROADCAST is defined (at least in my local copy of the Android NDK) to be `#define INADDR_BROADCAST ((unsigned long int) 0xffffffff)`, and the `unsigned long int` type is 64 bits on 64-bit platforms, but `BigDWord()` is expecting a 32 bit number. Explicitly doing the cast seems like the correct thing to do.

**Comment by WolfDan** [comment]
Thank you @aiusepsi !

Yeah that was the issue, casting INADDR_BROADCAST to uint32 solves it, I'll try to do a pr once I've test all android and ios builds so I fix that and add cmake support for android and ios

**Comment by GuillemDomenech** [comment]
Hi @WolfDan , do you mind sharing how you were able to build this library for iOS and Android on Windows?

**Comment by WolfDan** [comment]
@GuillemDomenech it's been a really long time since I did it, so I'm not sure if still being a valid solution, but you can find all my github actions for compiling it here 

https://github.com/WolfDan/UdpRelease/tree/master/.github/workflows

you can compile android with vcpkg on windows, as for iOS you need a mac for that like everything related with apple environment 

Again it's been years so I'm not sure if what I did still helpful

**Comment by GuillemDomenech** [comment]
Thanks for your reply, I will see if I can replicate what you did in your workflows locally. Hopefully it works!

**Comment by GuillemDomenech** [comment]
Hi @WolfDan , thanks to your repo I was able to compile on android and generate the .so files. 

![image](https://github.com/ValveSoftware/GameNetworkingSockets/assets/36267216/5bdf0de8-700b-4195-9edd-71f6a52a22fe)

But now I am having some issues with Unity recognising the library. When I build the apk for Android in Unity, I get an error after calling a function like this one:

`[DllImport("GameNetworkingSockets", CallingConvention = CallingConvention.Cdecl)] 
        internal static extern bool GameNetworkingSockets_Init(IntPtr identity, StringBuilder errorMessage);`
        
`Unable to load DLL 'GameNetworkingSockets'. Tried the load the following dynamic libraries: Unable to load dynamic library 'GameNetworkingSockets' because of 'Failed to open the requested dynamic library (0x06000000) dlerror() = dlopen failed: library "GameNetworkingSockets" not found`

It's like it can't find the library by its name, do you know why it might be?

@zpostfacto any idea?
