### ISSUE TITLE
Assertion Failed: packet number not properly initialized!

### ISSUE THREAD

**Issue by SDGNelson** [ValveSoftware/GameNetworkingSockets#156]
Several hosts have been reporting this assertion in standard output these past few days. Perhaps an issue introduced in the December 21st Steam client update?

Here is a full example from the log:

`src\steamnetworkingsockets\clientlib\steamnetworkingsockets_connections.cpp (1935) : Assertion Failed: [#579068838 UDP steamid:76561198963144398@XXXX:51905] packet number not properly initialized!`

**Comment by fletcherdvalve** [comment]
Thanks, I'll take a look.  I've been trying to nail initialization of this packet number for a while.  I am 99.9% sure the code heals this situation, so the assertion is harmless, but I'll take a look into it.

**Comment by synoga** [comment]
Hi @fletcherdvalve 

Did you have by any chance some time to have a look at this issue? I am facing the exact same behavior with the Windows build of my application, Linux build works fine though. Both are using the GameNetworkingSockets built from tag `v1.2.0`.

**Comment by fletcherdvalve** [comment]
@synoga Do you have a reliable way to reproduce this?

**Comment by synoga** [comment]
I can try to extract some minimal example code from my project, I'll let you know If I can reproduce it this way :). I've tried to remove the assertion and the windows build could connect without issues, and the communication seems ok.

**Comment by fletcherdvalve** [comment]
Yes, it's been my expectation that the assertion is a noisy irritation but doesn't actually cause any problems, which is why I haven't been prioritizing this.  If you can reliably reproduce it, or if it's actually causing connectivity issues, I'll bump this up.

**Comment by synoga** [comment]
While trying to reproduce, I rebuilt GNS on the server part of my application, and now I can't reproduce anymore, so I suspect I had some issue on that environment and that reminds me I should probably finish my CI ^^'

**Comment by TeemoCell** [comment]
Error still there
`/data/src/steamnetworkingsockets/clientlib/steamnetworkingsockets_connections.cpp (1935) : Assertion Failed: [#831113844 UDP steamid:76561198361366853@82.76.227.126:30437] packet number not properly initialized!`
That message lags my server really bad.

**Comment by zpostfacto** [comment]
Is anyone still getting this?  @SDGNelson @TeemoCell

**Comment by SDGNelson** [comment]
I'll ask around a bit

**Comment by SDGNelson** [comment]
It sounds like it is resolved!
One host with 38 servers even ran a search on the past year of logs and didn't find any mention of this assertion.

**Comment by zpostfacto** [comment]
Great!  No idea when it got fixed.  Thanks for looking.
