### ISSUE TITLE
Cmake issue with gns & vcpkg on Windows

### ISSUE THREAD

**Issue by Turtwiggy** [ValveSoftware/GameNetworkingSockets#158]
Hi there,
I'm trying to add GNS to my current project using VCPKG. The only slight difference I have going on is that I've used both VCPKG and GNS as submodules for my current project - which I installed using :
`.\thirdparty\vcpkg\vcpkg.exe --overlay-ports=.\thirdparty\GameNetworkingSockets\vcpkg_ports\ install gamenetworkingsockets:x64-windows`

```
PS C:\Programming\FightingGame>     .\thirdparty\vcpkg\vcpkg.exe --overlay-ports=.\thirdparty\GameNetworkingSockets\vcpkg_ports\ install gamenetworkingsockets:x64-windows
Computing installation plan...
The following packages are already installed:
    gamenetworkingsockets[core,openssl]:x64-windows -> 2020-10-06
Package gamenetworkingsockets:x64-windows is already installed

Total elapsed time: 359.4 us

The package gamenetworkingsockets:x64-windows provides CMake targets:

    find_package(GameNetworkingSockets CONFIG REQUIRED)
    target_link_libraries(main PRIVATE GameNetworkingSockets::shared GameNetworkingSockets::static GameNetworkingSockets::GameNetworkingSockets GameNetworkingSockets::GameNetworkingSockets_s)
```

This seems to work ok.

When I use `find_package(GameNetworkingSockets CONFIG REQUIRED)` as suggested by vcpkg, I am unable to build the project with the below error:

```
[cmake] game_3d finding package... GameNetworkingSockets
[cmake] CMake Error at thirdparty/vcpkg/installed/x64-windows/share/gamenetworkingsockets/GameNetworkingSocketsConfig.cmake:39 (if):
[cmake]   if given arguments:
[cmake] 
[cmake]     "STREQUAL" "package"
[cmake] 
[cmake]   Unknown arguments specified
[cmake] Call Stack (most recent call first):
[cmake]   thirdparty/vcpkg/scripts/buildsystems/vcpkg.cmake:634 (_find_package)
[cmake]   game_3d/CMakeLists.txt:15 (find_package)
[cmake] 
[cmake] 
[cmake] -- Configuring incomplete, errors occurred!
[cmake] See also "C:/Programming/FightingGame/build/CMakeFiles/CMakeOutput.log".
[cmake] See also "C:/Programming/FightingGame/build/CMakeFiles/CMakeError.log".

```

I checked the line in the GameNetworkingSocketsConfig.cmake:39, and it's trying to compare a blank string - so something messed up when this .cmake file was generated.

![image](https://user-images.githubusercontent.com/15272027/103482011-32780a80-4dd6-11eb-85a4-d075b1b47357.png)

Also, the "C:/Programming/FightingGame/build/CMakeFiles/CMakeError.log" contains 
```
Determining if the include file pthread.h exists failed with the following output:
Change Dir: C:/Programming/FightingGame/build/CMakeFiles/CMakeTmp

Run Build Command(s):C:/ProgramData/chocolatey/bin/ninja.exe cmTC_cafd3 && [1/2] Building C object CMakeFiles\cmTC_cafd3.dir\CheckIncludeFile.c.obj

FAILED: CMakeFiles/cmTC_cafd3.dir/CheckIncludeFile.c.obj 

C:\Software\MICROS~3\2019\COMMUN~1\VC\Tools\MSVC\1427~1.291\bin\Hostx64\x64\cl.exe  /nologo   /DWIN32 /D_WINDOWS /W3  /MDd /Zi /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\cmTC_cafd3.dir\CheckIncludeFile.c.obj /FdCMakeFiles\cmTC_cafd3.dir\ /FS -c CheckIncludeFile.c

CheckIncludeFile.c(1): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory
ninja: build stopped: subcommand failed.
```
which could be the real error, but not sure if it's unrelated.

I kinda hope I'm missing somthing obvious - not sure if this is a gns issue, or a setup issue on my side so any help would be appreciated. Thanks!

Again, not sure if this helps in any way, but the entire project with all it's cmake setup can be seen here: https://github.com/Turtwiggy/Cplusplus_game_engine

**Comment by aiusepsi** [comment]
Oops, yeah, there's definitely a bug in the generation of that file. You can delete lines 39-41 in GameNetworkingSocketsConfig.cmake to temporarily fix the issue. 

I'll look into properly fixing it, thanks for the report.

**Comment by Turtwiggy** [comment]
Thanks for the quick reply! Can confirm that deleting those lines let me build for one project.

I've noticed one more weird thing! I'm using VS Code Cmake Tools to build multiple cmake projects; but gns seems to be not liking this. Sorry about the tiny screenshot.

![image](https://user-images.githubusercontent.com/15272027/103483096-e11f4980-4ddc-11eb-93f5-81f829b45882.png)

And on the (new) GameNetworkingSocketsConfig.cmake:41:

![image](https://user-images.githubusercontent.com/15272027/103483115-0ca23400-4ddd-11eb-9c1d-0c5ea703810e.png)

**Comment by aiusepsi** [comment]
Ah, thanks for that report too. I think I see what's happened there, but I'll have to confirm the hunch.

**Comment by aiusepsi** [comment]
If you replace lines 41-49 with the following: 

```if(${CMAKE_VERSION} VERSION_GREATER_EQUAL "3.11.0")
    get_target_property(GNS_IMPORTED_GLOBAL_SET GameNetworkingSockets::GameNetworkingSockets IMPORTED_GLOBAL)

    if(NOT ${GNS_IMPORTED_GLOBAL_SET})
        set_target_properties(
            GameNetworkingSockets::GameNetworkingSockets GameNetworkingSockets::GameNetworkingSockets_s
            PROPERTIES IMPORTED_GLOBAL True
        )
    endif()

    unset(GNS_IMPORTED_GLOBAL_SET)

    add_library(GameNetworkingSockets::shared ALIAS GameNetworkingSockets::GameNetworkingSockets)
    add_library(GameNetworkingSockets::static ALIAS GameNetworkingSockets::GameNetworkingSockets_s)
endif()
```

that might do the trick. I've not set up a repro yet, though, so can't confirm it.

**Comment by Turtwiggy** [comment]
That did the trick! no issues building now :)
