### ISSUE TITLE
ConnectByIPAddress, UserData

### ISSUE THREAD

**Issue by yamashi** [ValveSoftware/GameNetworkingSockets#162]
Hello,

I am moving my codebase to 1.2.0 and need to upgrade to the new callbacks. 
As I understand it one needs to pass the callback via SteamNetworkingConfigValue_t, that's fine but the issue is how to pass userdata. The documentation says that callbacks may be called before the function returns, meaning I need to set the user data before or in ConnectByIPAddress but I can't find a way to do so. I really don't want to rely on a static pointer somewhere.

Best,
Max

**Comment by fletcherdvalve** [comment]
Hm.  I understand the goal here, to be able to set the userdata atomically.  I was about to say, "Good idea!" and add it to the todo list.  But then I realized that this only solves the problem for locally created connections.  It doesn't solve it for remotely-initiated connections, and in fact I'm not sure if there really is a good solution possible at all.  Consider this sequence of events:

1.) Connection is received at network layer.  A state change notification is posted to the queue (with zero user data)
2.) Remote host immediately changes its mind, or there is some problem with the connection.  Another state change callback is posted.   (Again with zero userdata.)
3.) Local code checks for / processes callback.

I don't have a good solution here.  What do you think?

Note that for messages, this problem doesn't happen.  If you change the userdata, we will go back and change any messages in the receive queue.  And you cannot receive a message until you have accepted it.

**Comment by yamashi** [comment]
I did realize that accepting a connection does lead to a brand new connection, I initially thought that the first event would be triggered by the listening handle but it's not the case.
I see a few options:
- When a brand new connection is created, trigger the event like done right now but also pass the listener socket so that we can grab the userdata associated with it.
- Pass a "cookie" via the opt structure that is always passed to the event handler (which I think would be the best solution)
- Inherit the userdata of the listener when a new connection is created.

**Comment by fletcherdvalve** [comment]
I've got a partner running into a similar issue.  I've got some ideas on a good way to add this.

**Comment by fletcherdvalve** [comment]
I think ab5ef56aa2cfadf897c8977695436ffb8d8d3ad0 should do what you need.  Let me know if it isn't what you were expecting
