### ISSUE TITLE
Setting the config value option "k_ESteamNetworkingConfig_Callback_ConnectionStatusChanged" seems not working?

### ISSUE THREAD

**Issue by LeventSevgili** [ValveSoftware/GameNetworkingSockets#166]
Before the commit [5523b24] i was able to set the below option for the Client app to connect to the Server to listen the callback instead of global callback. (global callback is working okay).

```
SteamNetworkingConfigValue_t opt;
		opt.SetPtr(k_ESteamNetworkingConfig_Callback_ConnectionStatusChanged, (void*)OnSteamNetConnectionStatusChanged);
		vecOpts.push_back(opt);

g_hConnection = SteamNetworkingSockets()->ConnectP2PCustomSignaling( pConnSignaling, &identityRemote, g_nVirtualPortRemote, (int)vecOpts.size(), vecOpts.data() );
```
After the commit [5523b24], ConnectP2PCustomSignaling method returns null with the above config.

I can replicate the case when i replace the GlobalCallback approach by the above code within the test_p2p.cpp at _test_p2p_ project, and build and run it.

In other words, i was able to use Network Config Option for "k_ESteamNetworkingConfig_Callback_ConnectionStatusChanged" for the client app instead of the GlobalCallback approach before [5523b24] commit.

When i digged in, i see the below switch case block at EvaluateScopeConfigValue method at csteamnetworkingsockets.cpp returns null (pConn)

```
case k_ESteamNetworkingConfig_Connection:
{
	// NOTE: Not using GetConnectionByHandleForAPI here.  In a few places in the code,
	// we need to be able to set config options for connections that are being created.
	// Really, we ought to plumb through these calls to an internal interface, so that
	// we would know that they should be given access.  Right now they are coming in
	// the "front door".  So this means if the app tries to set a config option on a
	// connection that technically no longer exists, we will actually allow that, when
	// we probably should fail the call.
	CSteamNetworkConnectionBase *pConn = GetConnectionByHandle( HSteamNetConnection( scopeObj ), connectionLock );
	if ( pConn )
	{
		if ( pEntry->m_eScope == k_ESteamNetworkingConfig_Connection )
		{
			return GetConnectionVar<T>( pEntry, &pConn->m_connectionConfig );
		}
	}
	break;
}
```

So i get a null pointer from ConnectP2PCustomSignaling at upmost level.

Question is; 
Is it possible to use the "k_ESteamNetworkingConfig_Callback_ConnectionStatusChanged" option instead of SteamNetworkingUtils()->SetGlobalCallback_SteamNetConnectionStatusChanged method with the latest commit or any after [5523b24] ?

Also i forgot to mention that, i'm building for and testing on Windows 10 with VS 2019.

Thank you very much!

**Comment by fletcherdvalve** [comment]
I'll take a look next week.

**Comment by LeventSevgili** [comment]
Great! Tested just in case. Thanks it worked!
