### ISSUE TITLE
steamnetworkingcustomsignaling.h missing from Steamworks SDK 1.51

### ISSUE THREAD

**Issue by rlabrecque** [ValveSoftware/GameNetworkingSockets#168]
https://github.com/ValveSoftware/GameNetworkingSockets/blob/ae52d2d0ce8d088fb7bb5a95225cdc97c8538b50/include/steam/steamnetworkingcustomsignaling.h

Hey Fletcher, seems like this file is missing from the 1.51 Steamworks SDK release?

**Comment by fletcherdvalve** [comment]
To be honest I don't want to ship the file with the SDK if I can avoid it.  An extremely small set of users might needs, and I want to talk to them to understand what they need first.

Is this causing problems?

(BTW, the opensource version of the file is compatible.)

**Comment by rlabrecque** [comment]
All good! Was mostly just confusion from upgrading from 1.50 to 1.51 since 1.50 had the contents of it!
