### ISSUE TITLE
API Feature Request: C style interface for steamnetworkingcustomsignaling C++ abstract class

### ISSUE THREAD

**Issue by Manquia** [ValveSoftware/GameNetworkingSockets#169]
Hello, I am working on bindings for JAI to the GameNetworkingSockets. In pursuit of that goal, I found that the ISteamNetworkingConnectionSignaling interface is not accessible/hard/(impossible?) to handle since JAI (like C) doesn't support abstract classes.

Can you please provide a C-style interface for the custom signaling API?

Thanks,
Micah Rust

**Comment by fletcherdvalve** [comment]
I could make a plain C function that creates an implementation of ISteamNetworkingConnectionSignaling, given a set of function pointers and a context object.   Shouldn't be too hard.

**Comment by Manquia** [comment]
Yep. That is basically what I was hoping for, Thanks.

**Comment by rlabrecque** [comment]
Would appreciate and use this in Steamworks.NET as well too 👍

**Comment by fletcherdvalve** [comment]
@rlabrecque Working on this.  Out of curiosity - some of the matchmaking APIs have this same design, right?  How are they currently handled?

**Comment by fletcherdvalve** [comment]
@Manquia @rlabrecque Let me know what you think.

**Comment by Manquia** [comment]
Sorry, it's taken so long to reply. I've been focused on another project and been unable to get the time to properly test this out. It looks good, but I've not tested it yet. I am hoping sometime this weekend or next that I'll have time to update my bindings to test the changes you've made.
