### ISSUE TITLE
Assertion Failed: Application didn't accept or close incoming connection in a reasonable amount of time.

### ISSUE THREAD

**Issue by TeemoCell** [ValveSoftware/GameNetworkingSockets#170]
src/steamnetworkingsockets/clientlib/steamnetworkingsockets_connections.cpp (2807) : Assertion Failed: Application didn't accept or close incoming connection in a reasonable amount of time.  This is probably a bug.

**Comment by TeemoCell** [comment]
Getting that error on an Unturned server. Console don't accept any input anymore.

**Comment by fletcherdvalve** [comment]
This means that there was an incoming connection, but the application code didn't do anything with it in a timely fashion, so whoever is trying to connect just dropped because.  It's probably not a bug in this library, although if you have some more logs or something I'd be happy to investigate.
