### ISSUE TITLE
Initial FreeBSD port - VALVE_CALLBACK_PACK_SMALL

### ISSUE THREAD

**Issue by osen** [ValveSoftware/GameNetworkingSockets#176]
Hi there,

I have recently put together a port for FreeBSD [here](https://www.freshports.org/net/gamenetworkingsockets).

In general this was very straight forward, presumably due to the work [here](https://github.com/ValveSoftware/GameNetworkingSockets/commit/0203aa732b19c7fa4a7a95b977c34e01c54d3a43).

One minor patch ([attached](https://github.com/ValveSoftware/GameNetworkingSockets/files/6578465/patch-include_steam_steamclientpublic.h.txt)) that I did have to make was in the conditional compilation in steamclientpublic.h [here](https://github.com/ValveSoftware/GameNetworkingSockets/blob/master/include/steam/steamclientpublic.h#L1260). Otherwise there was a compile time assertion error in terms of structure size.

Is checking for individual operating systems like this the best way? Would it perhaps be best to check for architecture / compiler? The FreeBSD port uses the default system compiler (Clang) rather than GCC but it still has many compatibility features added.

Obviously FreeBSD supports some weird and wonderful acrhitectures. I have only tested amd64 and i386. It is understandable you guys are only interested in a subset of platforms.

Either way, please feel free to use my very minor patch. Otherwise I can maintain the patch myself downstream.

Thanks!

**Comment by fletcherdvalve** [comment]
Looks good.  You want to submit a PR or at least tell me the proper email address to use, I'll tag you as the author.

**Comment by fletcherdvalve** [comment]
Actually --- this change should not affect the opensource code, right?

**Comment by osen** [comment]
Hi.

The goal was mainly to get it building (and working). I did see the **STEAMNETWORKINGSOCKETS_OPENSOURCE** define but tracing through where that gets set, I assumed it was for a different purpose.

That define always gets set [here](https://github.com/ValveSoftware/GameNetworkingSockets/blob/master/include/steam/steamnetworkingtypes.h#L21) and yet, unless I missed something, this never gets included before the point of my patch.

I can't see anything in the CMakeLists where this gets set either. Now I am almost certain I have missed something. Especially since this whole section is for legacy ABI compat (of which FreeBSD doesn't have a big back catalogue of Valve software to worry about). I will investigate this a little further soon.

**Comment by fletcherdvalve** [comment]
That include order seems to be is straight-up bug.

So I'm not sure if the correct solution is to fix this bug and make the packing consistent on all platforms in the opensource code (which is intended but currently not happening), or to try to maintain compatibility (both the content of the header files, and the ABI) with the Steamworks code.  I've actually expended energy towards the latter, and in fact that effort is probably currently only working because of this include order bug.

So I think I'll just remove the #ifdef STEAMNETWORKINGSOCKETS_OPENSOURCE in steamclient.h, and apply your patch.

The whole issue of the different structure packing is.....extremely unfortunate.  A very bad mistake that was made years ago and unfortunately cannot be corrected now.

**Comment by osen** [comment]
Hmm, I see. Also a nice reassurance I wasn't just being dense. ;)

My patch is a quick fix but possibly another solution could be to add a CMake option "OPENSOURCE" that sends through the STEAMNETWORKINGSOCKETS_OPENSOURCE define to the compiler flags and avoids the backwards compatibility code paths?

Looking through the rest of the code, I don't see too many cases like this however so perhaps the OPENSOURCE conditionals are unnecessary unless you foresee more areas like this in the future. Sometimes keeping the CMake build system as simple as possible is nice.

If this isn't high priority, let me know which you intend to go for and I am happy to spend a bit of time on it. I have the FreeBSD build server moaning at me for a few other things relating to this project anyway.
