### ISSUE TITLE
v1.3.0 failed to compile with set(CMAKE_CXX_EXTENSIONS OFF) on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by gtnardy** [ValveSoftware/GameNetworkingSockets#177]
Hello there, since v1.3.0 the build started failing to compile if I set `set(CMAKE_CXX_EXTENSIONS OFF)`, this is not a big deal for me as I could remove that flag from my external CMAKEFILE (which called the GameNetworkSockets afterwards).

But I don't know if this is something to be concerned about, I just though in warning you guys ;)

> gcc 9.3
> CMAKE_CXX_STANDARD 17
> CMAKE_CXX_STANDARD_REQUIRED ON

Here it follows the error which happens (there are many like this):

![image](https://user-images.githubusercontent.com/6226807/120925286-4211bd00-c6ae-11eb-92c2-9b3ff3433bee.png)

**Comment by fletcherdvalve** [comment]
I seem to remember that the token paste there is a non-standard-but-commonly-supported workaround for passing empty __VA_ARGS__.  I cannot remember what the status is on newer C++ spec, directly supporting empty __VA_ARGS__ and not needing this kludge, but.....perhaps there's a way to detect newer compilers, or at least use a different workaround for that particular compiler?  If you have an idea I'd be interested in a PR.

**Comment by fletcherdvalve** [comment]
I don't think there's a good solution for this, so I think I'm just gonna punt.

If there is an important use case that doesn't have an easy workaround, let me know, and we can reopen this or talk about how to solve it.
