### ISSUE TITLE
OSX CI builds - tests don't compile or run

### ISSUE THREAD

**Issue by zpostfacto** [ValveSoftware/GameNetworkingSockets#178]
All of the CI builds are flavors of linux.  It'd be great to add some Windows / Mac ones.

Anybody know github actions and want to help out?

**Comment by imerr** [comment]
I actually set that up on a fork the other day to get some mac binaries, just a "quick & dirty" setup 
Might still be of interest to you/anyone looking at the issue though https://github.com/imerr/GameNetworkingSockets/commit/a6f1534ad5d10ac24536db258a086ba31eadd6f7

**Comment by JeetRabari** [comment]
Sounds interesting !!! I would like to help.

**Comment by djdron** [comment]
I know how to do it with appveyor (windows).
Mac version can be built with osxcross inside linux docker.
[Here is how I build it](https://github.com/djdron/UnrealSpeccyP/blob/master/appveyor.yml).

**Comment by fletcherdvalve** [comment]
7b1fbfbb3b7e4f23f050661b407d49e13b3a2b18 adds CI for windows.

Changing the title since only OSX remains.

**Comment by AminSojoudi** [comment]
@zpostfacto 
Added a pull request for this.
https://github.com/ValveSoftware/GameNetworkingSockets/pull/326
I'm new here, if it does not work as expected, please let me know.

**Comment by zpostfacto** [comment]
I'm changing the title because the OSX tests aren't compiling or running, but at least we are compiling the library.
