### ISSUE TITLE
[Question]Are there any code style guidelines I can follow?

### ISSUE THREAD

**Issue by h53** [ValveSoftware/GameNetworkingSockets#185]
I notice that you name a variable with Cap C and I, Java style, I think it is a good format. I'm new in C++, So is there code standerd in Valve or, any standerd book you would recommand? thanks!

**Comment by fletcherdvalve** [comment]
When it comes to style, I think you just need to jump into a codebase and mimic what you see around you, and don't spend more than 1% of your your time/energy thinking about it.

The Valve style was not my style when I came here, and we're not terribly consistent even in our own code.
