### ISSUE TITLE
Need cmake to "install" cert tool to proper location

### ISSUE THREAD

**Issue by ELKABILLA** [ValveSoftware/GameNetworkingSockets#186]
When running the 'vcpkg' building, i was looking to the tests provided and realized that **steamnetworkingsockets_certtool**.exe was missing, **GameNetworkingSockets**.dll althougt was sucessfully created.  So i have a simple question: 
-- Is this behaviour intended on purpose or it has not been included into this build proccess ?
Thanks in advance.

Building on Windows x64

**Comment by fletcherdvalve** [comment]
I don't think anybody outside of Valve has used any of the PKI, to be honest.  So this tool (and the PKI) does work, because we use it -- but you should know that you might be one of the first people to actually use it outside of Valve.

We probably should have a way to build it in cmake.

**Comment by ELKABILLA** [comment]
yes you're right indeed, i see your point. 
I was just wondering why it is being referenced in these tests if it doesnt build automatically in the project.
so i think my doubt has been clarified.

PD: anyone had this tool already compiled ?  so i can satiate my curiosity...

**Comment by fletcherdvalve** [comment]
Added the help wanted label.  This should be a pretty straightforward job for anybody with basic smake knowledge.

**Comment by fletcherdvalve** [comment]
You can now build the cert tool by initializing the picojson git submodule and passing -DBUILD_TOOLS=ON to cmake.  I could use some help from somebody who knows cmake and/or vcpkg to "publish/install" the tool in the appropriate place and integrate with vcpkg better.

**Comment by fletcherdvalve** [comment]
OK, dc80d53427a590b7466cd9b4d23b4c6747e76e64 fixes a compile issue on Windows.

The vcpkg.info file has a "feature" for tools.

So I think the last step is just that I just need to know the proper way to "install" the tool.  Changing the title of this bug to reflect what is missing.
