### ISSUE TITLE
Add "flat" interface

### ISSUE THREAD

**Issue by fletcherdvalve** [ValveSoftware/GameNetworkingSockets#19]
We should provide a "flat" C-style interface to make it easier to use this library in plain C, or bind to other languages.  (E.g. #7)

It should probably have the same flat function names as will be used in the Steamworks SDK, 

We'll need to figure out the best way to do the callbacks.

**Comment by JernejL** [comment]
Agreed, this would be much appreciated, or if a separate wrapper project is made, it would introduce this to many more platforms & languages, pascal, python, etc..

**Comment by rlabrecque** [comment]
Callbacks as they currently exist are /okay/ with the flat C-Style interface. Having the same functions as the Steamworks SDK would help a lot. If you can get those python scripts that Alan wrote which generates those out here then I'd be up to fixing them up for this, but it should be pretty trivial.

**Comment by fletcherdvalve** [comment]
I've added a flat interface.  I did it by hand, because for some of the functions, you don't need to pass the interface pointer, since it doesn't matter.

For callbacks, since the P2P ones are not relevant, I made a custom RunCallbacks that only does the connection status changed one.

When the upstream code gets moved into the SteamworksSDK, this might change slightly.

**Comment by rlabrecque** [comment]
For the SteamworksSDK version I'd personally love if they all took an interface pointer, makes automatic codegen much easier and would let me upgrade rlabrecque/Steamworks.NET quicker.

**Comment by fletcherdvalve** [comment]
Reopening this.  It isn't flat enough.

**Comment by fletcherdvalve** [comment]
@rlabrecque I've updated the flat interface.

The message structure is now a struct and not an interface.  It still has to be cleaned up after use, but that is plain C code.  I also changed all the names to match the SteamWorks convention, and they all take an intptr_t (I don't know why - but whatever the reason I guess it's best to just copy what is done there).

**Comment by fletcherdvalve** [comment]
@rlabrecque You seem like the expert on this - want to make the C# wrapper and send a pull request????? :)

**Comment by tycho** [comment]
Also any changes you'd like to make that would make it easier to wrap without frustration would be nice too!

**Comment by fletcherdvalve** [comment]
Closing this fir now.  While we absolutely want to make sure we don't require any C++ exports or linkage, I don't think right now that we want to set as a goal to get the flat interface to compile as plain C.  The use of CSteamID would be a big blocker I can see immediately, and there are probably others.  I don't think there's enough value in us doing that work right at this time.  None of the rest of the Steamworks SDK flat interface can be compiled as plain C, to my knowledge.

**Comment by Frooxius** [comment]
Hello,

Not sure if this is the right place to ask, but is there any possibility of adding the same flat interface to the Steamworks version as well?

I would like to use the ValveSockets C# to utilize the Steamworks version (while I wait for some features on the open source, like the NAT piercing) and from my understanding the interface should be the same.

However the latest available Steamworks DLL version (1.44) doesn't seem to export same symbols and only has the object oriented interface.
