### ISSUE TITLE
Build either shared or static

### ISSUE THREAD

**Issue by TheClonerx** [ValveSoftware/GameNetworkingSockets#191]
Currently there are ongoing efforts to package this library in the Conan Center Index [here](https://github.com/conan-io/conan-center-index/pull/7040).
One of the issues we are having is that this project builds both the static and shared version of the library, but we only package either of those.
I suggest adding two new options, `BUILD_SHARED` and `BUILD_STATIC` and for compatibility both defaulting to `ON`.

**Comment by fletcherdvalve** [comment]
Added BUILD_STATIC_LIB and BUILD_SHARED_LIB options
