### ISSUE TITLE
Discard duplicate packet numbers (and unreliable messages)

### ISSUE THREAD

**Issue by fletcherdvalve** [ValveSoftware/GameNetworkingSockets#20]
Currently duplicate packets are not explicitly detected and discarded.  This does pose some potential DoS/performance risk, but probably not huge.  Perhaps more importantly, it allows an unreliable message to be delivered more than once.

Given how easy it is to detect duplicate packets, it's probably worthwhile to make an API guarantee that unreliable messages will not be delivered twice.  That is a huge class of application bugs that often go undetected during testing, but then happen in the wild on the internet, that we could easily prevent.

As for out-of-order unreliable messages: I don't want to always drop them, because the application may be able to make use of them and we don't have enough context to make that judgement call here.  Should we add an option to prevent out of order delivery?  This gets complicated, describing exactly what the guarantees and behavior are, especially when reliable and unreliable are mixed.  So it's probably best to just minimize what guarantees we make.  We do provide message numbers to the application, so the application can make its own decisions pretty easily.

But there is no value in duplicate delivery, for sure, so let's always discard.

**Comment by Mellnik** [comment]
Is this repo dead yet?

**Comment by fletcherdvalve** [comment]
@Mellnik There's a lot of work going on in another branch, addressing the first item on the roadmap.
https://github.com/ValveSoftware/GameNetworkingSockets/commits/snp-rewrite

**Comment by h1z1** [comment]
@fletcherdvalve Are you open to comments or is it pretty much a done deal?  Asking because if indeed you're basing it on QUIC, I think there is a misunderstanding about their intent.  Not sure even Google knows what they were smoking^Wthinking.  It's faster but fragile,  completely falls apart on some networks.

**Comment by fletcherdvalve** [comment]
@h1z1 I would definitely be interested in your opinions.  I would say the main thing we got from Google QUIC was just the high-level idea to use packet-level acks instead of a simple sliding window.  We didn't do the ACK encoding exactly like they did, we just used the basic idea that a richer ack protocol would result in less backing up and re-transmission.  I've tested the code we have under some pretty horrendous simulated network conditions and it survives.  (Although I haven't directly compared it to TCP yet.)

It is definitely more complicated than sliding window, I agree 100% on that.  My assumption is that spending a bit more more CPU and memory to reduce re-transmission is the correct tradeoff right now for most use cases.

You can take a look at the encoding and approach in the snp_rewrite branch now.
https://github.com/ValveSoftware/GameNetworkingSockets/blob/snp-rewrite/src/steamnetworkingsockets/clientlib/SNP_WIRE_FORMAT.md

**Comment by fletcherdvalve** [comment]
Fixed.

**Comment by nxrighthere** [comment]
@fletcherdvalve I wonder, will the messages always strictly delivered in order?
