### ISSUE TITLE
How to set connection timeout time?

### ISSUE THREAD

**Issue by Soaku** [ValveSoftware/GameNetworkingSockets#205]
I'm clearly missing something, so this is just a question.

When I close the client for my game forcefully, it takes a long time before the server removes the dead connection and I'd like to reduce that time. I've tried the below: 

(I'm using [my D bindings](https://github.com/Samerion/GameNetworkingSockets-D), so the below code is in D)

```d
auto success = GameNetworkingSockets_Init(null, error);
enforce(success, error.format!"Failed to initialize Steam GameNetworkingSockets: %s");
                                                                                       
const timeout = 1000;
                                                                                       
// Configure connections
auto utils = SteamNetworkingUtils();
utils.SetConfigValue(
    ESteamNetworkingConfigValue.TimeoutConnected,
    ESteamNetworkingConfigScope.Global,
    0,
    ESteamNetworkingConfigDataType.Int32,
    &timeout
);
```

However, the code above has no effect (yet the function returns `true`). I've also tried doing this after accepting each connection, of course using the appropriate scope and passing the connection ID instead of `0`. 

I'm not sure what am I doing wrong. Any hints?

**Comment by fletcherdvalve** [comment]
That value actually measures the time from when a "timeout condition" first is detected, to the time when we give up and consider the connection dropped.  So there needs to be something to trigger the code to think something is wrong.  Basically that means one side sends a packet to which a response is expected.  There are a few different types of such messages, but the most important are keepalives and reliable data.  

Currently the keepalive is hardcoded at 10s and cannot be configured.

However, if you need more frequent keepalives, you could just send any reliable message.

Let me know if that helps.  It might be reasonable feature to make the keepalive interval configurable, but I don't know when I'd be able to get around to it.  If you can modify the code for your use case, and don't need it to be configurable at runtime, you could just adjust the value of ``k_usecKeepAliveInterval``

**Comment by Soaku** [comment]
I see, that's helpful. Doing it manually sounds simple enough. Thank you!
