### ISSUE TITLE
Make a new release with connection userdata fix

### ISSUE THREAD

**Issue by jseward** [ValveSoftware/GameNetworkingSockets#208]
Would be great if the version `vcpkg` pulls down included this fix, just got caught up by it now.

https://github.com/ValveSoftware/GameNetworkingSockets/commit/657fb7a7fe57e3e4fcf406998a6242591c35bb2d

**Comment by fletcherdvalve** [comment]
Just a note that I do intend to make a new release soon, but I wanted to fix all the vcpk issues and get all that ship-shape first, and that's not really my area of expertise so it's kind of slow going.

**Comment by fletcherdvalve** [comment]
v1.4.0 released

**Comment by fletcherdvalve** [comment]
Actually, I'll leave this open until the vcpkg portfile has been updated.

**Comment by fletcherdvalve** [comment]
This finally got done....

https://github.com/microsoft/vcpkg/commit/2588a2e9790f86f2a58750e9911f9888db5996a2
