### ISSUE TITLE
Custom global allocator for message payloads

### ISSUE THREAD

**Issue by Kodpact** [ValveSoftware/GameNetworkingSockets#209]
Currently message payloads that are received on connection are allocated and freed using 'malloc'/'free'.
But, I want to use different allocator such as mimalloc.

Would be great if this gets added as general option (_SteamNetworkingUtils()->SetGlobalConfigValuePtr_)

**Comment by garyttierney** [comment]
Hey,

You can do this today by calling `SteamNetworkingSockets_SetCustomMemoryAllocator` with a custom allocator, but it requires that the library is built with `STEAMNETWORKINGSOCKETS_ENABLE_MEM_OVERRIDE`. See: https://github.com/ValveSoftware/GameNetworkingSockets/blob/f98cd32f62877d31a3fe27fc91578e13f4f795c9/include/steam/steamnetworkingsockets.h#L31

**Comment by Kodpact** [comment]
There are some global variables like
https://github.com/ValveSoftware/GameNetworkingSockets/blob/f98cd32f62877d31a3fe27fc91578e13f4f795c9/src/steamnetworkingsockets/clientlib/steamnetworkingsockets_connections.cpp#L735

That is getting allocated before I get change to call `SteamNetworkingSockets_SetCustomMemoryAllocator `
Which results in calling a null pointer. Could I be doing something wrong...

**Comment by fletcherdvalve** [comment]
Yeah, it is really a shame that std::vector's default constructor will sometimes allocate memory on some platforms and configurations.  Kindof a serious design flaw imo.  That workaround seems right.  I'll look into changing that static variable.  Any allocations made by that array are usually very small and transient, so probably not that important to track.
