### ISSUE TITLE
Manual callback dispatch missing

### ISSUE THREAD

**Issue by msvbg** [ValveSoftware/GameNetworkingSockets#215]
It seems that the functions for manually dispatching callbacks (e.g. `SteamAPI_ManualDispatch_Init`, `SteamAPI_ManualDispatch_GetNextCallback`, and `SteamAPI_ManualDispatch_GetAPICallResult`) are not available in the open source version of GameNetworkingSockets, though they are part of the closed-source Steam SDK. Are there any plans of making these part of the open source library?

**Comment by fletcherdvalve** [comment]
Steam callbacks are not used at all if you are using the opensource library.
There's a totally different dispatch mechanism.
See `ISteamNetworkingSockes::RunCallbacks()`

**Comment by msvbg** [comment]
Thanks for the response, closing this for now.
