### ISSUE TITLE
Assigning source port

### ISSUE THREAD

**Issue by JadeVand** [ValveSoftware/GameNetworkingSockets#216]
Hello, this is more of a question rather than an issue but how would I go about assigning a source port ? Is there a similar to bind function in GameNetworkingSockets?

Essentially, I'd like to send a request to a STUN server then it listen on the port it returns back to allow P2P.

**Comment by fletcherdvalve** [comment]
There's not currently a method to bind the socket used for an outbound UDP connection to a particular local port.  It probably wouldn't be too difficult to add one using a configuration variable.  I can add this as a feature request.

If this is a server port you must specify the local port.

But something tells me if the purpose is to do UDP connections after manually punching NAT or obtaining a server reflexive address, we should first figure out if the existing P2P support using WebRTC's NAT traversal can work for you.

**Comment by JadeVand** [comment]
Thank you for the reply,

Yes what I was hoping to do was send a UDP request outside of GameNetworkingSockets and once the public IP:Port is received, bind to that port and create a listening socket.

Can you elaborate more on the existing P2P support? I'd be fine with using my own STUN server wether or not it required GameNetworkingSockets.

**Comment by JadeVand** [comment]
Thank you for the reply,

Actually now that I think about the design of my architecture, it would be redundant for the client to be bound to a specific local port. Instead I think what needs to happen is each client should act as a listen server along with the host. Then a rendezvous server can send the public ip of all the clients to the host and the host's ip to each client. Then the host and client attempt a bidirectional connect on each-other to perform a NAT Punch? But I'm not sure how to go about doing that with this library. 

This is essentially the design I was thinking of:

```
Rendezvous and STUN servers are both public 

Host listens on local port 27020 - behind NAT
Host requests public ip from STUN server
Host sends public ip to rendezvous server
Client listens on local port 27021 - behind NAT
Client requests public ip from STUN server
Client sends public ip to rendezvous server
Client receives public ip of host
Host receives public ip of client
Host attempts to punch client ip:27021 
Client attempts to punch host ip:27020
Client connects to host
Host connects to client
```

Can you elaborate more on the existing P2P support?

**Comment by fletcherdvalve** [comment]
Did you see this?

https://github.com/ValveSoftware/GameNetworkingSockets/blob/master/README_P2P.md
