### ISSUE TITLE
Wrong number formatting.

### ISSUE THREAD

**Issue by angelskieglazki** [ValveSoftware/GameNetworkingSockets#219]
Hello, my colleague and I found a small bug in displaying statistics.
Zero is lost in the highest three digits.
For example, if we display the number of transmitted packets equal to 107898, then the result displayed on the screen will be: 17,898

This is small patch for fix this:
https://github.com/ValveSoftware/GameNetworkingSockets/blob/fd7e657ad9d226ec428c7e4b298444d8029de273/src/steamnetworkingsockets/steamnetworkingsockets_internal.h#L489
```
bool nz = false;
if ( iVal >= 100 ) { *(d++) = char( iVal/100 + '0' ); iVal %= 100; nz = true; }
if ( iVal >= 10 || nz ) { *(d++) = char( iVal/10 + '0' ); iVal %= 10; }
```

**Comment by fletcherdvalve** [comment]
Ah yes, good find!
