### ISSUE TITLE
Can I use its UDP to transfer files, there are about 500 files, each file is about 3M

### ISSUE THREAD

**Issue by seamanm** [ValveSoftware/GameNetworkingSockets#220]
Can I use its UDP to transfer files, there are about 500 files, each file is about 3M

Will the transmission speed be faster than TCP? Do we have similar usage scenarios？
thanks

**Comment by zpostfacto** [comment]
Sorry, I don't really have any info on whether the library will work well for that case.  It wasn't really designed for that purpose.
