### ISSUE TITLE
Ambiguous documentation for ConfigureConnectionLanes

### ISSUE THREAD

**Issue by Meoo** [ValveSoftware/GameNetworkingSockets#224]
Documentation for ConfigureConnectionLanes is ambiguous:

See https://github.com/ValveSoftware/GameNetworkingSockets/blob/master/include/steam/isteamnetworkingsockets.h#L394

It is stated that

> [for priority] higher numeric values take priority over lower numeric values.

and right after, in the example:

> with priorities [ 0, 10, 10 ] [...] messages sent on the first will always be sent first, before messages in the other two lanes.

The test code in test_connection.cpp seems to confirm that lower numeric values have higher priority, so the example seems to be correct, and the documentation seems to be incorrect.

**Comment by copyrat90** [comment]
It seems that the [corresponding Steamworks Documentation](https://partner.steamgames.com/doc/api/ISteamNetworkingSockets#ConfigureConnectionLanes) is still incorrect.
