### ISSUE TITLE
Utilizing ISteamNetworkingMessage 

### ISSUE THREAD

**Issue by JadeVand** [ValveSoftware/GameNetworkingSockets#227]
I'm trying to port my code over to GameNetworkingSockets and `ISteamNetworkingMessages` would make the porting easier, since it acts like sendto and recvfrom where the address (identity) is provided on each request; however I can't really find much documentation on using `ISteamNetworkingMessages`.

I'm unsure where to create the socket for the interface, since the ReceiveMessagesOnChannel doesn't take a socket argument, neither does SendMessageToUser.

This is what I understand so far what I can do 
```
    ISteamNetworkingMessages* pSNMessageInterface = SteamNetworkingMessages();
    for(;;)
    {
        SteamNetworkingMessage_t* pIncomingMessage = NULL;
        int nMessages = pSNMessageInterface->ReceiveMessagesOnChannel(0,&pIncomingMessage,1);
        assert(nMessages == 0 || nMessages == 1);
        if(nMessages>0)
        {
            pIncomingMessage->Release();
        }
    }
```
But this isn't complete so I don't know where to create the listen socket for the reciver or the sender socket for the client..

A code example with ISteamNetworkingMessage would be really helpful. 

And thank you for keeping up with the project.

**Comment by zpostfacto** [comment]
There are no listen sockets or "connections" when you use this interface.  The exist, but it's under the hood.  How are you sending messages?

The big questions here are going to be:
1.) How are peers identified (what is their identity?).  ISteamNetworkingMessages doesn't work with IPAddress identities.  (Although it would be possible to make that work.  But then really the only thing you are getting above raw sendto/recv calls is the fragmentation and reassembly and retransmission of reliable messages.)
2.) If these are P2P connections that might need to be NAT-punched, how are the rendezvous signals delivered?  (See README_P2P.md)

**Comment by JadeVand** [comment]
Thank you for the response. I suppose my issue was I was trying to use IPAddress identities with ISteamNetworkingMessages. Would you then recommend I look at another method? Ideally what I'd like to do is have a single socket, but able to specify the destination of the messages or receive messages on a single socket, very much like sendto and recvfrom. 

I did look into the symmetric connections which behaves as both a connection and a listener socket but I'm unsure if this would solve my problem. Unless I can connect to the rendezvous , then internally change the destination if it's tied to the socket and have it point elsewhere. Is that possible?
