### ISSUE TITLE
After killing and re-initting the Library for POSIX, a static flag seems not restored for a specific case.

### ISSUE THREAD

**Issue by LeventSevgili** [ValveSoftware/GameNetworkingSockets#230]
Hey Greetings,

First of all, i want to say that i'm months back from current branch. I had a case and I just quickly read the current code and i believe the thing seems still there and i wanted to mention it here. If it is already handled, i'm sorry for taking time :/.

I have a case that; when i destroy GameNetworkingSockets by `GameNetworkingSockets_Kill();` and re-init it at the very same app session, then connect to the very same server, it starts to give many but same assertion failures. Btw I'm at POSIX platform, and i'm using P2P connection to the server. 

When i debugged it i realized it is because `s_bRecreatePollList` at `steamnetworkingsockets_lowlevel.cpp` seems not restored, when the GameNetworkingSockets is destroyed. So when i connect second time, it starts to give assertion failure.

When i dived in, I realized the Poll list is not recreated for the second time of the GameNetworkingSockets, because the s_bRecreatePollList is not set to true after the kill. So `s_vecPollFDs `vector is not populated with the new socket ids and gives the below assertion failure. Thanks to the Assertion there, it gives the signal.

https://github.com/ValveSoftware/GameNetworkingSockets/blob/b221ac1a1cde2ae9af2a93f53511490ba94678da/src/steamnetworkingsockets/clientlib/steamnetworkingsockets_lowlevel.cpp#L2142

As a fix, i added below code to the `SteamNetworkingSocketsLowLevelDecRef ` method, because `SteamNetworkingSocketsLowLevelDecRef `is called after i call `GameNetworkingSockets_Kill();` and so it resets the s_bRecreatePollList flag.

```
#ifndef _WIN32
       s_bRecreatePollList = true;
#endif
```

So after adding the above, it worked nicely, no assertion failure after the second connection.

Well, on the other hand, `s_bRecreatePollList `is already restored on some methods, and i debugged them, but they did not get called, i think it may be because it is a P2P Connection, i haven't tested it yet. 

So my roughly assumption is; if it is POSIX and P2P Connection, `s_bRecreatePollList  `is not restored after `GameNetworkingSockets_Kill();` So when you connect second time after the Kill, it gives assertion fail.

Hope it helps somehow. Thank you very much!
Cheerzz ^^.

**Comment by zpostfacto** [comment]
Thanks.  That code has been refactored quite a bit in the last month or so, but I'll see if I can spot a place where we have the same basic bug in the new code.
