### ISSUE TITLE
Crash on Android

### ISSUE THREAD

**Issue by hayate0106** [ValveSoftware/GameNetworkingSockets#231]
I build the library successed on android. But crash occurred at function EVP_DigestSignUpdate.

**Comment by zpostfacto** [comment]
Not much to go on here.  Do you have any more info?

**Comment by zpostfacto** [comment]
If you have some more info (what openssl version was being used, stack trace, etc) we can reopen this bug and investigate some more.  Since we really don't even have a supported way to BUILD android right now (I would love to!) I'm not sure how to really investigate this bug.

Regarding building android - if you had to make any changes to the cmake files, etc, I would love to have those changes.

**Comment by hayate0106** [comment]
> If you have some more info (what openssl version was being used, stack trace, etc) we can reopen this bug and investigate some more. Since we really don't even have a supported way to BUILD android right now (I would love to!) I'm not sure how to really investigate this bug.
> 
> Regarding building android - if you had to make any changes to the cmake files, etc, I would love to have those changes.
I'm sorry to reply so late. I build it by cmake just like you said. Here is the crash dump.

********** Crash dump: **********
Build fingerprint: 'Xiaomi/sagit/sagit:7.1.1/NMF26X/V9.0.5.0.NCACNEI:user/releas
e-keys'
#00 0xfb1b7788 <unknown>
#01 0x00208117 /data/app/com.YourCompany.C2World-1/lib/arm/libGameNetworkingSock
ets.so (EVP_DigestSignUpdate+178)

        EVP_DigestSignUpdate

        D:\development\GameNetworkingSockets-1.4.0\vcpkg\buildtrees\openssl\arm-
android-dbg\3.0.3-ba651081cb.clean\crypto/evp\m_sigver.c:429:17
#02 0x0018bf1d /data/app/com.YourCompany.C2World-1/lib/arm/libGameNetworkingSock
ets.so
CCrypto::GenerateHMAC256(unsigned char const*, unsigned int, unsigned char const
*, unsigned int, unsigned char (*) [32])
D:/development/GameNetworkingSockets-1.4.0/src/common\crypto_openssl.cpp:450:2
#03 0x001528d5 /data/app/com.YourCompany.C2World-1/lib/arm/libGameNetworkingSock
ets.so
SteamNetworkingSocketsLib::CSteamNetworkConnectionBase::FinishCryptoHandshake(bo
ol, char (&) [1024])
D:/development/GameNetworkingSockets-1.4.0/src/steamnetworkingsockets/clientlib\
steamnetworkingsockets_connections.cpp:1654:2
#04 0x0015260d /data/app/com.YourCompany.C2World-1/lib/arm/libGameNetworkingSock
ets.so
SteamNetworkingSocketsLib::CSteamNetworkConnectionBase::RecvCryptoHandshake(CMsg
SteamDatagramCertificateSigned const&, CMsgSteamDatagramSessionCryptInfoSigned c
onst&, bool, char (&) [1024])
D:/development/GameNetworkingSockets-1.4.0/src/steamnetworkingsockets/clientlib\
steamnetworkingsockets_connections.cpp:1549:10
#05 0x001755e7 /data/app/com.YourCompany.C2World-1/lib/arm/libGameNetworkingSock
ets.so
SteamNetworkingSocketsLib::CConnectionTransportUDP::Received_ConnectOK(CMsgSteam
Sockets_UDP_ConnectOK const&, long long)
D:/development/GameNetworkingSockets-1.4.0/src/steamnetworkingsockets/clientlib\
steamnetworkingsockets_udp.cpp:1657:54
#06 0x00173f27 /data/app/com.YourCompany.C2World-1/lib/arm/libGameNetworkingSock
ets.so
SteamNetworkingSocketsLib::CConnectionTransportUDP::PacketReceived(SteamNetworki
ngSocketsLib::RecvPktInfo_t const&, SteamNetworkingSocketsLib::CConnectionTransp
ortUDP*)
D:/development/GameNetworkingSockets-1.4.0/src/steamnetworkingsockets/clientlib\
steamnetworkingsockets_udp.cpp:1390:10
#07 0x0015cc9d /data/app/com.YourCompany.C2World-1/lib/arm/libGameNetworkingSock
ets.so
SteamNetworkingSocketsLib::CRecvPacketCallback::operator()(SteamNetworkingSocket
sLib::RecvPktInfo_t const&) const
D:/development/GameNetworkingSockets-1.4.0/src/steamnetworkingsockets/clientlib\
steamnetworkingsockets_lowlevel.h:83:4
SteamNetworkingSocketsLib::PollRawUDPSockets(int, bool)
D:/development/GameNetworkingSockets-1.4.0/src/steamnetworkingsockets/clientlib\
steamnetworkingsockets_lowlevel.cpp:2006:0
SteamNetworkingSocketsLib::SteamNetworkingSockets_InternalPoll(int, bool)
D:/development/GameNetworkingSockets-1.4.0/src/steamnetworkingsockets/clientlib\
steamnetworkingsockets_lowlevel.cpp:2545:0
#08 0x0015bbc7 /data/app/com.YourCompany.C2World-1/lib/arm/libGameNetworkingSock
ets.so
SteamNetworkingSocketsLib::SteamNetworkingThreadProc()
D:/development/GameNetworkingSockets-1.4.0/src/steamnetworkingsockets/clientlib\
steamnetworkingsockets_lowlevel.cpp:2653:10
#09 0x0015dfe5 /data/app/com.YourCompany.C2World-1/lib/arm/libGameNetworkingSock
ets.so
decltype(std::__ndk1::forward<void (*)()>(fp)()) std::__ndk1::__invoke<void (*)(
)>(void (*&&)())
D:\android\android-ndk-r21e\toolchains\llvm\prebuilt\windows-x86_64\bin\..\sysro
ot\usr\include\c++\v1\type_traits:3501:1
void std::__ndk1::__thread_execute<std::__ndk1::unique_ptr<std::__ndk1::__thread
_struct, std::__ndk1::default_delete<std::__ndk1::__thread_struct> >, void (*)()
>(std::__ndk1::tuple<std::__ndk1::unique_ptr<std::__ndk1::__thread_struct, std::
__ndk1::default_delete<std::__ndk1::__thread_struct> >, void (*)()>&, std::__ndk
1::__tuple_indices<>)
D:\android\android-ndk-r21e\toolchains\llvm\prebuilt\windows-x86_64\bin\..\sysro
ot\usr\include\c++\v1\thread:273:0
void* std::__ndk1::__thread_proxy<std::__ndk1::tuple<std::__ndk1::unique_ptr<std
::__ndk1::__thread_struct, std::__ndk1::default_delete<std::__ndk1::__thread_str
uct> >, void (*)()> >(void*)
D:\android\android-ndk-r21e\toolchains\llvm\prebuilt\windows-x86_64\bin\..\sysro
ot\usr\include\c++\v1\thread:283:0
#10 0x00047817 /system/lib/libc.so (_ZL15__pthread_startPv+22)
#11 0x00019f95 /system/lib/libc.so (__start_thread+6)
Crash dump is completed
