### ISSUE TITLE
IGameServersService Interface

### ISSUE THREAD

**Issue by PhilCarterL** [ValveSoftware/GameNetworkingSockets#246]
Interface: https://partner.steamgames.com/doc/webapi/IGameServersService
wiki: https://developer.valvesoftware.com/wiki/Master_Server_Query_Protocol
Request URL: https://api.steampowered.com/IGameServersService/GetServerList/v1/?key=SteamWebAPIKey&limit=50000&filter=\gamedir\csgo\nand\1\gametype\valve_ds\dedicated\1

There is no information about working with "CLOUD_SERVER_CONTROLLER" in the documentation. Why is this scaling devkit not described?

<img src="https://gcdnb.pbrd.co/images/lccoJW6tJifS.png?o=1" width="800">

Is this some kind of new devkit? since I see that it is duplicated more than 10,000 times having the same information, but in partner.steamgames.com I can't find any information

**Comment by zpostfacto** [comment]
Sorry for now seeing this.  Those APIs don't really have anything to do with this library.
