### ISSUE TITLE
Why protobuf?

### ISSUE THREAD

**Issue by bugproof** [ValveSoftware/GameNetworkingSockets#253]
It would be good if protobuf dependency could be made optional.

Is protobuf just used internally or is there any public API that expects protobuf structs? Could you explain for what is it used exactly? I quickly ran through the code and it seems like it's used mostly for connection related messages and statistics.

> What it does not do:
> Higher level serialization of entities, delta encoding of changed state variables, etc

But it still requires protobuf

**Comment by zpostfacto** [comment]
The wire protocol uses protobuf internally in several places, and cannot really be made optional.
