### ISSUE TITLE
Steam Client change causes excessive logging and contention on `SteamNetworkingSockets` calls, causing stutter on multiple games.

### ISSUE THREAD

**Issue by Dietr1ch** [ValveSoftware/GameNetworkingSockets#254]
#### Your system information

* Steam client version (build number or date): About says it's built at 2022-08-17 18:23:53
* Distribution: NixOS. I'm tracking the unstable channel and installing Steam with `home-manager`. I'm using some real-time patches too, which show a significant fps boost on cs:go.
* Opted into Steam client beta?: Opted out, but the issue started happening on Stable too.
* Have you checked for system updates?: Yes, just updated and verified it's still a problem.

#### Please describe your issue in as much detail as possible:
I started getting stutter on cs:go, every ~3s the game would freeze and the fps would drop from ~300 to under 15.
The game console would complain about `SteamNetworkingSockets` lock being held for 500+ms ([Last issue I found with that symptom](https://github.com/ValveSoftware/GameNetworkingSockets/issues/165), this seems different though).

I tried updating, using a newer kernel w/o the RT patches, but the issue remains.
I investigated a bit and noticed that Steam is wasting an entire thread logging, and that by launching the Steam client via Krunner I'd also fill my system logs and cause journald to give me trouble.

The line being logged by the Steam client is,
> ```
> ioctl (SFEATURE): No route to host
> ```

There's something wrong, but I can't tell exactly why because the line doesn't even try to explain the context on which that error happens ([Heroku's best practices around logging](https://devcenter.heroku.com/articles/writing-best-practices-for-application-logs) may come up useful).

Also I don't know why you'd log without any throttling, which is what causes contention. Running steam from fish and dropping the logs (`steam &>/dev/null`) made things playable, but not anymore.

Can we get all error messages throttled and make them informative to aid debugging?

**Comment by kisak-valve** [comment]
Hello @Dietr1ch, since the issue is fairly well scoped, I suspect it's more appropriate for the issue tracker that I've transferred this issue report to. If that isn't the case then a relevant dev can give me a nudge to transfer this back to the steam-for-linux issue tracker.

**Comment by Dietr1ch** [comment]
Thanks! It seems it belongs here for now.

**Comment by Dietr1ch** [comment]
I'd like to provide more info, but I'm not sure how to tell which version of this library I'm running, nor how to swap-in a custom fresh build.

**Comment by Dietr1ch** [comment]
I found that the logging is just a bad side-effect, but that I still have issues when I throw the logs away.

However, I did found that by disabling Steam networking (`Steam Client Menu > Steam > Settings > In-Game > Steam Networking = Never`) *and* restarting Steam the problem went away.

This might be only an issue under bad network setups (like double NAT?), otherwise people wouldn't be playing at all because at least on CS:GO I end up wanting to destroy my computer more than to play.

**Comment by zpostfacto** [comment]
Where is the logging actually appearing?  Is it stderr, syslog?

I have a feeling this doesn't have anything to do with SteamNetworkingSockets.  I think it's probably something else blocking SteamNetworkingSockets (grepping the code, it might be some input stuff?  Although I cannot find anything that would produce that output anywhere).  SteamnetworkingSockets is the only lib that is foolish enough to complain when there's bad perf, so everybody always assumes the cause is in the lib, when it's almost always upstream.

**Comment by zpostfacto** [comment]
Hm, another possible culprit is the WebRTC library trying to do NAT punch.

**Comment by Dietr1ch** [comment]
> Where is the logging actually appearing? Is it stderr, syslog?

stderr

> I have a feeling this doesn't have anything to do with SteamNetworkingSockets. I think it's probably something else blocking SteamNetworkingSockets (grepping the code, it might be some input stuff? Although I cannot find anything that would produce that output anywhere). SteamnetworkingSockets is the only lib that is foolish enough to complain when there's bad perf, so everybody always assumes the cause is in the lib, when it's almost always upstream.

If this is the case, then this might be yet another red herring.


I'm not sure how to get better understanding of the logs, it seems that at some point the error gets logged to stderr without enough context, and whoever is relying on the calls that trigger that error is not handling errors properly (assuming that the API will return some kind of error instead of silently logging).

I tried disabling the Steam Networking (Steam > Settings > In-Game) with no luck.
Another symptom I see, is that just starting Steam and minimizing it to the tray takes between 35% to 65% of a core.
Is there any way I could provide you with useful CPU profiles? I'm guessing that better information on why Steam permanently uses/wastes a core might lead us to the right issue.


I'll try to play with the network later today (6h+). I'm currently under a double NAT because the router my ISP uses is too crappy.

**Comment by Dietr1ch** [comment]
To make things interesting, making my machine sleep made the issue go away :thinking:. The CPU 35%-65% is no longer wasted by steam, and I no longer see the stderr logs.

Given how consistent it was before, I'd guess that restarting my machine might bring the issue back.

**Comment by Dietr1ch** [comment]
I think that the bug got fixed, I can't reproduce this. There's no more High CPU usage and the error is not on stderr anymore.

**Comment by mohd-akram** [comment]
I see this issue in TF2 running on Wineskin.
