### ISSUE TITLE
Is checksum needed for reliable message?

### ISSUE THREAD

**Issue by ifshuaishuai** [ValveSoftware/GameNetworkingSockets#256]
TCP is a reliable stream-oriented, but there maybe encounter some Network Bit-Flip issue:
1. [Amazon S3 Availability Event: July 20, 2008](https://web.archive.org/web/20220403060108/https://status.aws.amazon.com/s3-20080720.html)
2. [The Limitations of the Ethernet CRC and TCP/IP checksums for error detection](http://noahdavids.org/self_published/CRC_and_checksum.html)

So, how reliable is this transport layer works? Is checksum needed in my code?

**Comment by zpostfacto** [comment]
If the default encryption is not disabled, then it provides extremely strong protection against random bit errors and tampering. Much stronger than a simple CRC.
