### ISSUE TITLE
Who to contact to get consoles code?

### ISSUE THREAD

**Issue by AdrienVR** [ValveSoftware/GameNetworkingSockets#258]
Hello,
I am using GameNetworkingSockets for networking in the game OctaFight and I'm very happy about it, it works very well on Steam.
The README page says "This library has shipped on consoles, mobile platforms, and non-Steam stores, and has been used to facilitate cross-platform connectivity. Contact us to get access to the code. (We are not allowed to distribute it here.)".
I contacted Steam weeks ago through Support Steam/Steamworks but I didn't get any answer.
Could you clarify who to contact for this?
Thanks!

**Comment by zpostfacto** [comment]
This is a dup of #187.

And I'm sorry I have a backlog of tickets that I have not answered about this.  I will try to clear all those out.  (I realize it has been ages and I'm sorry, but I think we just now know what the answer is to these questions.)

**Comment by AdrienVR** [comment]
Thanks, I'm not sure on how the ticket system is working, so just to make sure, my ticket is here: https://help.steampowered.com/fr/wizard/HelpRequest/HT-8NPF-GWFK-572C
