### ISSUE TITLE
sample server and client

### ISSUE THREAD

**Issue by peererror** [ValveSoftware/GameNetworkingSockets#26]
Any demo client or server for getting started

**Comment by ryoung9550** [comment]
When the project builds it creates a test_connection executable. This test demos the server and client. The source for the code is in tests/test_connection.cpp

**Comment by fletcherdvalve** [comment]
I added a really simple IRC-like application that demonstrates how to make connections, send and receive messages, and check for connection status changes.

It sends all messages reliable, which is not really very game-like.  But it does demonstrate a lot of the basics.

The connection test code is really not a good example.

**Comment by gtnardy** [comment]
hey there, where can I find the IRC example application?

**Comment by gtnardy** [comment]
> 
> 
> I added a really simple IRC-like application that demonstrates how to make connections, send and receive messages, and check for connection status changes.
> 
> It sends all messages reliable, which is not really very game-like. But it does demonstrate a lot of the basics.
> 
> The connection test code is really not a good example.

hey there, where can I find the IRC example application? @fletcherdvalve
