### ISSUE TITLE
Question: IPC functionality

### ISSUE THREAD

**Issue by tomwjerry** [ValveSoftware/GameNetworkingSockets#260]
I tried to search but to no avail. Does this support IPC (Inter-process communication)? I guess that it does since the documentation says "Head-of-line blocking control and bandwidth sharing of multiple message streams ('lanes') on the same connection". I am looking for a way to create communication between servers that might be on the same computer.

**Comment by zpostfacto** [comment]
I think you could do this by making a connection to an address on the same host.  (e.g. 127.0.0.1)
