### ISSUE TITLE
Question: steam

### ISSUE THREAD

**Issue by hychn** [ValveSoftware/GameNetworkingSockets#261]
I have a question, the steam classes (ISteamNetworkingMessages) just seem to be abstractions.
Are they just there so I can build my program to fit with the steamnetworking API?
And I will plug it the steamnetworking API later?

Sorry if my question seems a bit basic... I am quite new to this.

**Comment by zpostfacto** [comment]
That is the interface exposed by the library.  You'll get an instance of one of those using a global accessor, for example the function `SteamNetworkingMessages()`

You won't implement a subclass.
