### ISSUE TITLE
k_ESteamNetworkingConfig_SendRateMin and Max have non zero defaults, but documentation says otherwise.

### ISSUE THREAD

**Issue by mvhooren** [ValveSoftware/GameNetworkingSockets#270]
In SteamNetworkingTypes.h :

/// [connection int32] Minimum/maximum send rate clamp, 0 is no limit.
/// This value will control the min/max allowed sending rate that 
/// bandwidth estimation is allowed to reach.  Default is 0 (no-limit)
k_ESteamNetworkingConfig_SendRateMin = 10,
k_ESteamNetworkingConfig_SendRateMax = 11,

In CSteamNetworkingSockets.cpp:

DEFINE_CONNECTON_DEFAULT_CONFIGVAL( int32, SendRateMin, 128\*1024, 1024, 0x10000000 );
DEFINE_CONNECTON_DEFAULT_CONFIGVAL( int32, SendRateMax, 1024\*1024, 1024, 0x10000000 );

**Comment by gtnardy** [comment]
I noticed that too.
And also: when setting it to `0` (which says it's unlimited), it actually limits it to 0 indeed. No packet is sent at all! 😅

**Comment by zpostfacto** [comment]
Yeah, that documentation was written when I thought I would have time to implement bandwidth estimation.  As you can see, I still have not, soooooo.  I will update the defaults and the documentation to match.
