### ISSUE TITLE
Not properly dropping packets when recv buffer full

### ISSUE THREAD

**Issue by SDGNelson** [ValveSoftware/GameNetworkingSockets#280]
Last week and over the weekend Unturned has received a couple support tickets from players getting disconnected from `ProblemDetectedLocally` with end reason 5002 and end debug string of "Reliable message size # too large for remaining space in message queue." In one log received # was 8, and in another it was 10.

Considering the documentation for `k_ESteamNetConnectionEnd_Misc_InternalError` says "Generic failure that is most likely a software bug." I wondered if I should open an issue here. Is this a software bug on my end, or in SteamNetworkingSockets?

It seems to only be affecting a handful of players. These players are consistently unable to play multiplayer, whereas other players are able to join the same servers just fine.

**Comment by zpostfacto** [comment]
This means that a bunch of data has been received and is sitting in the queue ready to be pulled out by the app, but the app is not processing it.  It usually means that the app is not processing messages fast enough to keep up with the amount of data the sender has sent.

You can get more information by enabling logging.  See ISteamnetworkingUtils::SetDebugOutputFunction

Or you can run the game with these environment variables set:
```
STEAMNETWORKINGSOCKETS_LOG_LEVEL=3
STEAMNETWORKINGSOCKETS_LOG_FILE=<filename>
```

If you really need the ability to buffer up a larger amount of received, you can adjust the recv buffer limits.  See 
```
k_ESteamNetworkingConfig_RecvBufferSize     <<< this is probably the one you need to raise
k_ESteamNetworkingConfig_RecvMaxMessageSize
k_ESteamNetworkingConfig_RecvMaxSegmentsPerPacket
```

However, I think you are right that there is a bug here, in that it's intended (and documentated!) that the library will simply drop the packets when the recv buffer is full, not abort the connection.  Until then, you can work around this by ensuring that you are emptying the queue in a timely manner, or increasing the recv buffer size.

**Comment by SDGNelson** [comment]
Thank you for these details and suggestions!

**Comment by zpostfacto** [comment]
Updated title to reflect what I think the real bug here is

**Comment by gtnardy** [comment]
Up on this.

It seems it started happening since the new Steam UI update, actually since it released in Beta I started noticing this on my game. 

But with the yesterday official release it got then this became a bigger problem as everyone is getting the update

**Comment by zpostfacto** [comment]
@gtnardy Are you saying that something broke recently with a steam client update?  The original bug does not refer to anything that changed recently as far as I know.  The behaviour has always been this way.  If you don't mind, would you describe exactly what error you are getting, and when you started seeing it?

**Comment by gtnardy** [comment]
> @gtnardy Are you saying that something broke recently with a steam client update? The original bug does not refer to anything that changed recently as far as I know. The behaviour has always been this way. If you don't mind, would you describe exactly what error you are getting, and when you started seeing it?

Yeah, let me contextualize.

I supposed it is related to this issue because me (and my players) were getting the error `Reliable message size X too large for remaining space in message queue` too when this new [Steam Desktop](https://store.steampowered.com/news/app/593110/view/3687931965598906184) version rolled out in the Beta branch of Steam while we were participating on the beta (+- 1 month ago).

Then, yesterday, when this new Steam Client update officially released, we all started to get this error again (when connecting to a server - moment when my game server sends a lot of data to clients)

**Comment by gtnardy** [comment]
@zpostfacto Sure thing, thanks, let me know when it's pushed!

**Comment by zpostfacto** [comment]
Despite the bug being closed, the fix has not shipped in the steam client yet, I'll let you know when that happens.

**Comment by zpostfacto** [comment]
@gtnardy We did ship a client beta yesterday.  Can you check if it fixes the issue for you?
https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/6627657351330751106

**Comment by gtnardy** [comment]
Thank you! I will tell my community to do some tests and let you know🙏
