### ISSUE TITLE
Update Steamworks web documentation

### ISSUE THREAD

**Issue by kulkalkul** [ValveSoftware/GameNetworkingSockets#281]
This probably isn't the correct way to ask, but I found it most straightforward.

I'm using Steamworks SDK, and I wonder about the possibility of having channels/lanes backported. I've read through Steamworks docs but couldn't find relevant information in ISteamNetworkingSockets. Any idea? Thanks!

**Comment by zpostfacto** [comment]
Lane support is available in the latest SDK.  The web documentation is probably just out of date.  I'll leave this bug open as a reminder to update the documentation.

**Comment by zpostfacto** [comment]
The web documentation has been updated to document multi-lane support
