### ISSUE TITLE
SendMessageToConnection succeeds, but ReceiveMessagesOnConnection returns 0 messages

### ISSUE THREAD

**Issue by alecdutch** [ValveSoftware/GameNetworkingSockets#282]
My team is using SteamNetworkingSockets for a game made in Unreal Engine 4 (UE4.27). Our setup is peer-to-peer, so clients connect directly to each other, and there's no single server hosting the game.

We've successfully gotten our clients to connect, and the clients get a successful response from Steam's API when calling SendMessageToConnection(), like in this example:
```
void FSteamSocket::Send(const uint8* Data, int32 Count, int32& BytesSent)
{
	BytesSent = 0;
	if (InternalHandle != k_HSteamNetConnection_Invalid && GetConnectionState() == SCS_Connected)
	{
		switch (SteamSocketsInterface->SendMessageToConnection(InternalHandle, (void*)Data, Count, SendMode, nullptr))
		{
			case k_EResultOK:
				UE_LOG(LogTemp, Display, TEXT("Success"));    //  <-------- This works, and outputs "Success"
			break;

			default:
				UE_LOG(LogTemp, Display, TEXT("Failure"));
			break;
		}
	}
}
```

However, the receiving client isn't receiving those messages, as far as I can tell. Here's an example of how we're calling the ReceiveMessagesOnConnection API and checking the data returned:
```
	int MaxMessages = 1;
	int MessagesRead = SteamSocketInterface->ReceiveMessagesOnConnection(InternalHandle, &Data, MaxMessages);

	UE_LOG(LogTemp, Display, TEXT("MessagesRead: %d"), MessagesRead); // <-------- always shows 0
```

Do you have any recommendations about how I can troubleshoot this? 

--------------------------

If it's relevant, we're using AcceptConnection() to accept the connection from another client when the event is received, but we don't do anything special to handle handshaking. I saw a note in the documentation for AcceptConnection [here](https://partner.steamgames.com/doc/api/ISteamNetworkingSockets#ReceiveMessagesOnConnection) that handshaking might be necessary in some cases (I'm guessing it's not necessary, but wanted to call it out just in case.)

Much appreciated!

**Comment by zpostfacto** [comment]
Setup a debug output function using ``ISteamNetworkingUtils::SetDebugOutputFunction`` and see if there is any information there.

You can also get logging each time a message is sent or received by doing something like this:

```SteamNetworjkingUtils()->SetGlobalConfigValueInt32( k_ESteamNetworkingConfig_LogLevel_Message, k_ESteamNetworkingSocketsDebugOutputType_Msg )```

**Comment by alecdutch** [comment]
Thanks!

I set up logging like this to get as much info as possible:
```
SteamNetworkingUtils()->SetDebugOutputFunction(DebugLevel, SteamSocketsDebugLogger);
SteamNetworkingUtils()->SetGlobalConfigValueInt32(k_ESteamNetworkingConfig_LogLevel_Message, k_ESteamNetworkingSocketsDebugOutputType_Everything);
```

When I send a message, I see this in the log. It shows the correct size of 4 (I just sent the word "ping"):
`[2023.05.27-01.29.53:488][186]LogSteamSocketsAPI: Verbose: SteamSockets API: Log [#1699237006 P2P SDR steamid:76561199507960572 vport 0] SendMessage UNRELIABLE: MsgNum=142 **sz=4**`

And when I receive a message, I see a corresponding entry in the log that shows the same size of 4:
`[2023.05.27-01.29.53:455][185]LogSteamSocketsAPI: Verbose: SteamSockets API: Log [#2875887150 P2P SDR steamid:76561199507960572 vport 0] RecvMessage MsgNum=146 **sz=4**`

But calling the code code below still results in MessagesRead being set to 0:
```
SteamNetworkingMessage_t* Data;
int MaxMessages = 1;
int MessagesRead = SteamSocketInterface->ReceiveMessagesOnConnection(InternalHandle, &Data, MaxMessages);

UE_LOG(LogTemp, Display, TEXT("MessagesRead: %d"), MessagesRead); // <-------- always shows 0
```

Any idea what could be going wrong here?

**Comment by zpostfacto** [comment]
Where is the InternalHandle shown above coming from?

**Comment by alecdutch** [comment]
I may have gotten this figured out:

The InternalHandle above was being stored when I called CreateListenSocketIP(). But I just noticed that AcceptConnection() returns a new handle, which UE4 uses to create a child socket.

UE4 normally uses a client-server model and includes some extra classes that handle connections behind-the-scenes (like USteamSocketsNetDriver). I've had to rework some things for our peer-to-peer setup, so I've included my new version of FSteamSocketsSubsystem::SteamSocketEventHandler below, in case someone else is trying to implement a custom setup like ours.

I'll go ahead and close this ticket- thanks for the help, @zpostfacto!

```
void FSteamSocketsSubsystem::SteamSocketEventHandler(struct SteamNetConnectionStatusChangedCallback_t* Message)
{
	if (Message == nullptr || FSteamSocketsSubsystem::GetSteamSocketsInterface() == nullptr)
	{
		return;
	}

	// New Connection came in
	if (Message->m_eOldState == k_ESteamNetworkingConnectionState_None &&
		Message->m_info.m_eState == k_ESteamNetworkingConnectionState_Connecting &&
		Message->m_info.m_hListenSocket != k_HSteamListenSocket_Invalid)
	{
		//Accept the connection using the API
		EResult AcceptedResult = FSteamSocketsSubsystem::GetSteamSocketsInterface()->AcceptConnection(Message->m_hConn);

		//Use our stored socket set in FSteamSocket::Listen() to accept the result (will create a child socket)
		//This code comes from NetDriver->OnConnectionCreated(), since our implementation does not using the NetDriver class
		if (ListeningSocket)
		{
			// Create the bookkeeping and set up the socket.
			FInternetAddrSteamSockets ConnectedAddr;
			FSteamSocket* NewSocket = static_cast<FSteamSocket*>(ListeningSocket->Accept(TEXT("AcceptedSocket")));
			NewSocket->InternalHandle = Message->m_hConn;

#if !PLATFORM_MAC
			// Hotfix-safe version, should get refactored into a separate function that also sets InternalHandle
			GetSteamSocketsInterface()->SetConnectionPollGroup(Message->m_hConn, ListeningSocket->PollGroup);
#endif // PLATFORM_MAC

			NewSocket->GetPeerAddress(ConnectedAddr);
			AddSocket(ConnectedAddr, NewSocket, ListeningSocket);

 			// Output info to confirm the handles
			UE_LOG(LogTemp, Error, TEXT(" FSteamSocketsSubsystem::SteamSocketEventHandler --- accepted connection: %llu, our internal handle: %llu"), Message->m_hConn, NewSocket->InternalHandle);
		}
	}
	else if ((Message->m_eOldState == k_ESteamNetworkingConnectionState_Connecting || Message->m_eOldState == k_ESteamNetworkingConnectionState_FindingRoute) &&
		Message->m_info.m_eState == k_ESteamNetworkingConnectionState_Connected)
	{
		//TODO: possibly handle this update case (didn't seem to be necessary from my testing)
	}
	else if ((Message->m_eOldState == k_ESteamNetworkingConnectionState_FindingRoute || Message->m_eOldState == k_ESteamNetworkingConnectionState_Connecting 
		|| Message->m_eOldState == k_ESteamNetworkingConnectionState_Connected) &&
		(Message->m_info.m_eState == k_ESteamNetworkingConnectionState_ClosedByPeer || Message->m_info.m_eState == k_ESteamNetworkingConnectionState_ProblemDetectedLocally))
	{
		//TODO: handle closing connection
	}
}
```
