### ISSUE TITLE
Comments that mention ISteamNetworkingMessages::FlushMessagesToUser

### ISSUE THREAD

**Issue by tuket** [ValveSoftware/GameNetworkingSockets#283]
In the file "steamnetworkingtypes.h" there are many documentation comments that refer to a function called `ISteamNetworkingMessages::FlushMessagesToUser`.
This function does not exist.

**Comment by tuket** [comment]
Btw, from what I've read in the docs, you should be able to use the NoNagle flags for flushing. However, I have tried to send a message without nagle and, if I close the application immediately, the msg doesn't get to the destination.

My use case would be: when a player closes the game, I would like to send a DISCONNECT msg to the other end and shutdown my game immediately (without waiting for confirmation). How do you achieve that?

**Comment by zpostfacto** [comment]
A few things:
- Good catch.  I'll make a note to either write that function or update the docs.
- If you care about cleaning up the "connection", you would probably be better off using a connection-oriented interface (one where you have an HSteamNetConnection).  You should basically think of `ISteamNetworkingMessages` as a replacement for UDP sentro/recv from.  For connection-oriented interfaces, there's usually no reason to send a "close message" - you just close the connection and the other side will get notified.
- Remember that this is an application layer protocol running on top of UDP.  It's not like a TCP connection where the operating system knows how to cleanup connections after you close them and terminate.  So if you terminate the app, we're done and we cannot really do any more cleanup.  You can fire off a message, but if that packet drops, the peer is not going to clean up the connection cleanly.
- I think the `k_nSteamNetworkingSend_NoNagle` flag should work properly when sending messages using `ISteamNetworkingMessages`

**Comment by tuket** [comment]
> I think the k_nSteamNetworkingSend_NoNagle flag should work properly when sending messages using ISteamNetworkingMessages

I solved my problem a while ago, but I think this was the solution. Cheers.
