### ISSUE TITLE
lets move to zpp::bits!?

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/GameNetworkingSockets#293]
hey, i would like to suggest zpp::libs because of how good it is:
![image](https://github.com/ValveSoftware/GameNetworkingSockets/assets/118131071/2ec3ebad-ec08-4326-ada2-5924736fa2a5)

zpp::libs go brrrr

**Comment by angelskieglazki** [comment]
I think this is not possible at the moment, because this library uses c++20

**Comment by natashaevans266** [comment]
Thank you for producing such a fascinating essay on this subject [pumpkin panic](https://pumpkinpanicgame.io). This has sparked a lot of thought in me, and I'm looking forward to reading more.
