### ISSUE TITLE
Request to add compression

### ISSUE THREAD

**Issue by mca222** [ValveSoftware/GameNetworkingSockets#304]
Although the gain for UDP can  be limited, are there any plans to add compression? Or pointers how to add it myself?

**Comment by zpostfacto** [comment]
I don't want to add compression right now.

This introduces a very large number of potential dependencies.  Everybody will have strong opinions about what library should be used, what the options should be.  We'll have a large number of requests "support my favorite library, please", etc.  Then we have a bunch of compatibility issues, and potentially back compat requirements to support old compression protocols indefinitely, etc.
