### ISSUE TITLE
How build for x32 solution (Visual Studio)

### ISSUE THREAD

**Issue by continue98** [ValveSoftware/GameNetworkingSockets#31]
Hi. How build GameNetworkingSocket for static x32 solution with Visual Studio?
Problems:
`c:\gamenetworkingsockets\src\steamnetworkingsockets\certtool\../steamnetworkings
ockets_internal.h(516): error C2143: синтаксическая ошибка: отсутствие "," перед
 "<"
c:\gamenetworkingsockets\src\steamnetworkingsockets\certtool\../steamnetworkings
ockets_internal.h(522): error C2039: set: не является членом "std"
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.
13.26128\include\functional(21): note:  см. объявление "std"
c:\gamenetworkingsockets\src\steamnetworkingsockets\certtool\../steamnetworkings
ockets_internal.h(522): error C4430: отсутствует спецификатор типа - предполагае
тся int. Примечание. C++ не поддерживает int по умолчанию
c:\gamenetworkingsockets\src\steamnetworkingsockets\certtool\../steamnetworkings
ockets_internal.h(522): error C2988: неопознанное объявление или определение шаб
лона
c:\gamenetworkingsockets\src\steamnetworkingsockets\certtool\../steamnetworkings
ockets_internal.h(522): error C2143: синтаксическая ошибка: отсутствие "," перед
 "<"
c:\gamenetworkingsockets\src\steamnetworkingsockets\certtool\../steamnetworkings
ockets_internal.h(776): error C2977: vstd::LikeStdVectorTraits: слишком много ар
гументов шаблон
c:\gamenetworkingsockets\src\steamnetworkingsockets\certtool\../steamnetworkings
ockets_internal.h(776): note:  см. объявление "vstd::LikeStdVectorTraits"
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(68): error C2039: vector: не является членом "std"
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.
13.26128\include\functional(21): note:  см. объявление "std"
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(68): error C2143: синтаксическая ошибка: отсутствие ";" перед "
<"
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(68): error C4430: отсутствует спецификатор типа - предполагаетс
я int. Примечание. C++ не поддерживает int по умолчанию
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(119): error C2065: s_vecDataCenterIDs: необъявленный идентифика
тор
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(120): error C3312: не найдена вызываемая функция "begin" для ти
па "unknown-type"
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(120): error C3312: не найдена вызываемая функция "end" для типа
 "unknown-type"
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(122): error C2065: id: необъявленный идентификатор
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(160): error C4430: отсутствует спецификатор типа - предполагает
ся int. Примечание. C++ не поддерживает int по умолчанию
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(160): error C2143: синтаксическая ошибка: отсутствие "," перед
"&"
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(164): error C2065: CMsgSteamDatagramCertificate: необъявленный
идентификатор
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(164): error C2146: синтаксическая ошибка: отсутствие ";" перед
идентификатором "msgCert"
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(164): error C2065: msgCert: необъявленный идентификатор
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(165): error C2065: msgCert: необъявленный идентификатор
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(165): error C2228: выражение слева от ".ParseFromString" должно
 представлять класс, структуру или объединение
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(165): note: тип: unknown-type
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(165): error C2065: msgSigned: необъявленный идентификатор
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(165): error C2228: выражение слева от ".cert" должно представля
ть класс, структуру или объединение
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(165): note: тип: unknown-type
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(168): error C2065: msgCert: необъявленный идентификатор
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(168): error C2228: выражение слева от ".key_data" должно предст
авлять класс, структуру или объединение
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(168): note: тип: unknown-type
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(168): error C2228: выражение слева от ".c_str" должно представл
ять класс, структуру или объединение
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(168): error C2228: выражение слева от ".length" должно представ
лять класс, структуру или объединение
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(168): error C2660: CCryptoKeyBase::Set: функция не принимает 1
аргументов
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(170): error C2065: msgCert: необъявленный идентификатор
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(170): error C2228: выражение слева от ".time_created" должно пр
едставлять класс, структуру или объединение
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(170): note: тип: unknown-type
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(171): error C2065: msgCert: необъявленный идентификатор
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(171): error C2228: выражение слева от ".time_expiry" должно пре
дставлять класс, структуру или объединение
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(171): note: тип: unknown-type
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(182): error C2065: msgCert: необъявленный идентификатор
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(182): error C2228: выражение слева от ".gameserver_datacenter_i
ds" должно представлять класс, структуру или объединение
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(182): note: тип: unknown-type
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(184): error C2065: id: необъявленный идентификатор
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(186): error C2065: pszJSONIndent: необъявленный идентификатор
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(202): error C2065: pszJSONIndent: необъявленный идентификатор
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(204): error C2065: pszJSONIndent: необъявленный идентификатор
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(205): error C2065: sOutResult: необъявленный идентификатор
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(208): error C2065: pszJSONIndent: необъявленный идентификатор
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(209): error C2065: sOutResult: необъявленный идентификатор
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(211): error C2065: pszJSONIndent: необъявленный идентификатор
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(212): error C2065: sOutResult: необъявленный идентификатор
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(213): error C2065: pszJSONIndent: необъявленный идентификатор
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(214): error C2065: sOutResult: необъявленный идентификатор
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(215): error C2065: pszJSONIndent: необъявленный идентификатор
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(215): error C2065: msgSigned: необъявленный идентификатор
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(215): error C2228: выражение слева от ".ca_key_id" должно предс
тавлять класс, структуру или объединение
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(215): note: тип: unknown-type
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(216): error C2065: sOutResult: необъявленный идентификатор
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(221): error C2065: sOutResult: необъявленный идентификатор
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(223): error C2065: sOutResult: необъявленный идентификатор
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(225): error C2065: sOutResult: необъявленный идентификатор
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(226): error C2065: msgSigned: необъявленный идентификатор
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(226): error C2228: выражение слева от ".ca_key_id" должно предс
тавлять класс, структуру или объединение
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(226): note: тип: unknown-type
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(227): error C2065: sOutResult: необъявленный идентификатор
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(231): error C2065: sOutResult: необъявленный идентификатор
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(242): error C2065: s_vecDataCenterIDs: необъявленный идентифика
тор
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(242): error C2228: выражение слева от ".size" должно представля
ть класс, структуру или объединение
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(242): note: тип: unknown-type
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(250): error C2065: CMsgSteamDatagramCertificate: необъявленный
идентификатор
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(250): error C2146: синтаксическая ошибка: отсутствие ";" перед
идентификатором "msgCert"
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(250): error C2065: msgCert: необъявленный идентификатор
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(251): error C2065: msgCert: необъявленный идентификатор
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(251): error C2228: выражение слева от ".set_key_type" должно пр
едставлять класс, структуру или объединение
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(251): note: тип: unknown-type
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(251): error C2065: CMsgSteamDatagramCertificate_EKeyType_ED2551
9: необъявленный идентификатор
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(252): error C2065: msgCert: необъявленный идентификатор
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(252): error C2228: выражение слева от ".set_key_data" должно пр
едставлять класс, структуру или объединение
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(252): note: тип: unknown-type
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(253): error C2065: msgCert: необъявленный идентификатор
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(253): error C2228: выражение слева от ".set_time_created" должн
о представлять класс, структуру или объединение
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(253): note: тип: unknown-type
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(254): error C2065: msgCert: необъявленный идентификатор
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(254): error C2228: выражение слева от ".set_time_expiry" должно
 представлять класс, структуру или объединение
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(254): note: тип: unknown-type
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(254): error C2228: выражение слева от ".time_created" должно пр
едставлять класс, структуру или объединение
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(254): note: тип: unknown-type
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(255): error C2065: s_vecDataCenterIDs: необъявленный идентифика
тор
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(256): error C3312: не найдена вызываемая функция "begin" для ти
па "unknown-type"
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(256): error C3312: не найдена вызываемая функция "end" для типа
 "unknown-type"
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(256): error C2065: msgCert: необъявленный идентификатор
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(256): error C2228: выражение слева от ".add_gameserver_datacent
er_ids" должно представлять класс, структуру или объединение
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(256): note: тип: unknown-type
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(256): error C2065: id: необъявленный идентификатор
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(259): error C2065: CMsgSteamDatagramCertificateSigned: необъявл
енный идентификатор
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(259): error C2146: синтаксическая ошибка: отсутствие ";" перед
идентификатором "msgSigned"
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(259): error C2065: msgSigned: необъявленный идентификатор
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(260): error C2065: msgSigned: необъявленный идентификатор
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(260): error C2228: выражение слева от ".set_cert" должно предст
авлять класс, структуру или объединение
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(260): note: тип: unknown-type
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(260): error C2065: msgCert: необъявленный идентификатор
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(260): error C2228: выражение слева от ".SerializeAsString" долж
но представлять класс, структуру или объединение
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(260): note: тип: unknown-type
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(263): error C2065: msgSigned: необъявленный идентификатор
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(263): error C2228: выражение слева от ".cert" должно представля
ть класс, структуру или объединение
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(263): note: тип: unknown-type
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(263): error C2228: выражение слева от ".c_str" должно представл
ять класс, структуру или объединение
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(263): error C2228: выражение слева от ".length" должно представ
лять класс, структуру или объединение
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(263): error C2660: CCrypto::GenerateSignature: функция не прини
мает 3 аргументов
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(264): error C2065: msgSigned: необъявленный идентификатор
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(264): error C2228: выражение слева от ".set_ca_key_id" должно п
редставлять класс, структуру или объединение
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(264): note: тип: unknown-type
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(265): error C2065: msgSigned: необъявленный идентификатор
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(265): error C2228: выражение слева от ".set_ca_signature" должн
о представлять класс, структуру или объединение
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(265): note: тип: unknown-type
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(267): error C2065: msgSigned: необъявленный идентификатор
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(267): error C2228: выражение слева от ".SerializeAsString" долж
но представлять класс, структуру или объединение
C:\GameNetworkingSockets\src\steamnetworkingsockets\certtool\steamnetworkingsock
ets_certtool.cpp(267): fatal error C1003: число ошибок превышает 100; остановка
компиляции
NMAKE : fatal error U1077: C:\PROGRA~2\MICROS~1\2017\ENTERP~1\VC\Tools\MSVC\1413
~1.261\bin\Hostx86\x86\cl.exe : возвращенный код "0x2"
Stop.
NMAKE : fatal error U1077: "C:\Program Files (x86)\Microsoft Visual Studio\2017\
Enterprise\VC\Tools\MSVC\14.13.26128\bin\HostX86\x86\nmake.exe" : возвращенный к
од "0x2"
Stop.
NMAKE : fatal error U1077: "C:\Program Files (x86)\Microsoft Visual Studio\2017\
Enterprise\VC\Tools\MSVC\14.13.26128\bin\HostX86\x86\nmake.exe" : возвращенный к
од "0x2"
Stop.

C:\GameNetworkingSockets\build>`

Please, help build for x32 solution with Visual Studio

**Comment by tycho** [comment]
I can't read Cyrillic. Please translate your error messages.

**Comment by tycho** [comment]
Please re-file your issue once you have messages in English so we can help troubleshoot the problem.

**Comment by janisozaur** [comment]
I highly doubt MSVC is capable of targeting [x32 ABI](https://en.m.wikipedia.org/wiki/X32_ABI) so perhaps that's the source of errors.

**Comment by tycho** [comment]
@janisozaur They're most likely referring to "x86" as "x32" because it seems like the logical counterpart to "x64". But seeing "x32" bugs me for the same reason.
