### ISSUE TITLE
test_p2p client failing

### ISSUE THREAD

**Issue by lolriven** [ValveSoftware/GameNetworkingSockets#315]
I'm running on a MacOS M1 compiling for ARM64

I have the trivial_signaling_server running on 0.0.0.0:10000

The client is executing with the following arguments
`./test_p2p --client --identity-local str:vel --identity-remote str:lev --signaling-server 0.0.0.0:10000`

The test immediately fails with the following message.

>   0.007345 Initialized low level socket/threading support.
>   0.010410 Connecting to 'str:lev', virtual port 0, from local virtual port 0.
>   0.010421 Creating signaling session for peer 'str:lev'
>   0.013193 [#7097424 P2P str:lev vport 0] Relay candidates enabled by P2P_Transport_ICE_Enable, but P2P_TURN_ServerList is empty
>   0.019533 SteamNetworkingSockets lock held for 9.0ms.  (Performance warning.)  ConnectP2PCustomSignaling,Base::BInitConnection,GetIdentity,FinalizeLocalCrypto,CSteamNetworkConnectionP2P::CheckInitICE,CConnectionTransportP2PICE_Valve::Init
> This is usually a symptom of a general performance problem such as thread starvation.
>   0.019549 Sending msg 'Greetings!'
>   0.019630 [#7097424 P2P str:lev vport 0] Entered connecting state
>   0.068053 src/steamnetworkingsockets/steamnetworkingsockets_thinker.cpp(199): Processed thinkers 10001 times -- probably one thinker keeps requesting an immediate wakeup call.
> Assertion failed: (!"TEST FAILED"), function DebugOutput, file test_common.cpp, line 50.
> zsh: abort      ./test_p2p --client --identity-local str:vel --identity-remote str:lev  
> 

I have tried compiling both USE_STEAMWEBRTC=ON and OFF

Note:
I tested this on a Windows x64 machine and the client and server executed correctly.

**Comment by JadeVand** [comment]
After some searching, I've found that in this loop 
```
void IThinker::Thinker_ProcessThinkers()
{
	// We need the lock to access the thinker queue
	s_mutexThinkerTable.lock();

	// Until the queue is empty
	int nIterations = 0;
	while ( s_queueThinkers.Count() > 0 )
	{
		// Grab the head element
		IThinker *pNextThinker = s_queueThinkers.ElementAtHead();

		// Refetch timestamp each time.  The reason is that certain thinkers
		// may pass through to other systems (e.g. fake lag) that fetch the time.
		// If we don't update the time here, that code may have used the newer
		// timestamp (e.g. to mark when a packet was received) and then
		// in our next iteration, we will use an older timestamp to process
		// a thinker.
		SteamNetworkingMicroseconds usecNow = SteamNetworkingSockets_GetLocalTimestamp();

		// Scheduled too far in the future?
		if ( pNextThinker->GetNextThinkTime() >= usecNow )
		{
			// Keep waiting
			break;
		}

		++nIterations;
		if ( nIterations > 10000 )
		{
			AssertMsg1( false, "Processed thinkers %d times -- probably one thinker keeps requesting an immediate wakeup call.", nIterations );
			break;
		}

```
There's nothing in there popping thinkers from the queue which could lead it to loop forever?
