### ISSUE TITLE
Question on licensing

### ISSUE THREAD

**Issue by a1batross** [ValveSoftware/GameNetworkingSockets#36]
I would like to fork tier1 from GameNetworkingSockets to provide a generic SourceSDK-styled template library. 

But does BSD license also applies for `src/tier1` and `src/public/tier1`? I see just Valve Software's copyrights in headers and no mention of BSD license.

**Comment by fletcherdvalve** [comment]
Sorry for the slow reply.  Everything in this project uses the same license, so do what you want with it.

But really, do you want to build on top of any of that stuff in here?  It's not really high quality code.  I mean it works just fine, don't get me wrong, and what's in here is battle-tested, sure.  But it's not organized in a useful way and it has an odd collection of functions that are just what this particular project needs.  I had to do really vicious things to the code to get it out of the Steam codebase and into a form it would even compile.
