### ISSUE TITLE
UDP-based Protocol Question

### ISSUE THREAD

**Issue by TimonPost** [ValveSoftware/GameNetworkingSockets#38]
Hey, I and my team are the creators of `[laminar](https://github.com/amethyst/laminar)` it is basically a protocol like a gaffer described on his website, written with rust, for the Amethyst game-engine. We saw that this library took some inspiration from there as well. We had some questions concerning the value of writing an own written semi-UDP-based protocol or using QUIC. 

Question being: why aren't you using QUIC as the protocol for game networking instead of your own custom semi-reliable UDP-base protocol? 

Why considering this? Well... because it is basically a well-defined protocol written by Google with high speed and alot of customizability and awesome features like congestion avoidance, fragmentation of packets, TLS 1.3 support, reliability, unreliability, order, unordered etc. 

I am very curious if you also maked a decision on this point, and why you choose for QUIC-Crypto only and left the rest of QUIC away?

**Comment by fletcherdvalve** [comment]
QUIC did not support unreliable messages when we started this project.  If we had to do over, we might use it.
