### ISSUE TITLE
Every AES encrypt/decrypt call is doing a heap allocation/free

### ISSUE THREAD

**Issue by fletcherdvalve** [ValveSoftware/GameNetworkingSockets#47]
Because EVP_CIPHER_CTX.

Holy crap.

We should find a way to not do this.

Anybody know a (simple, portable) way to avoid this?

**Comment by fletcherdvalve** [comment]
Actually, it's doing *multiple* allocations.

I checked in a custom allocator that will put them into an arena.  It made the CBC encryption about 10% faster on a Ubuntu VM I'm using.  We'll see what numbers @tycho comes up with for AES-GCM, on the allocation sizes we care about most.  If it's not a decent win, maybe back it out or make it an option?  Still, regardless of the numbers, it really bothers me to be making multiple heap calls per packet!

Maybe the heap is fast nowadays and I'm just a dinosaur.

**Comment by rlabrecque** [comment]
^ For reference: https://github.com/ValveSoftware/GameNetworkingSockets/commit/17c52cb0f09d310d958c233ff6b80c335cf2540e

**Comment by fletcherdvalve** [comment]
The numbers are in!

I am a dinosaur.

I'll back out that "optimization".  Closing this.

**Comment by TTimo** [comment]
Unreal uses jmalloc for the whole engine though.

**Comment by fletcherdvalve** [comment]
Re-opening this issue.  Just so I can officially close it for really realz.
