### ISSUE TITLE
Question about the order of reliable messages

### ISSUE THREAD

**Issue by felipejfc** [ValveSoftware/GameNetworkingSockets#53]
Hi!

It’s said in the documentation of the ReceiveMessages in connection and socket that it’s guaranteed that the messages will be received in the order they’re sent, but, is that still the case if retransmissions occurs?

Imagine this scenario:

Server send clients A, B, C

Client receives A and C but not B because it needed to be retransmited
Client calls receive messages on connection
Client receives B message
Client calls receive messages again

Will the lib hold the messages till B comes or will it deliver A C B?

Thanks

**Comment by fletcherdvalve** [comment]
Sorry, just now saw this.

Yes, reliable messages guarantee delivery order (with respect to other reliable messages).  Basically it is a TCP stream, but where the boundary between messages is relevant.

The order of delivery regarding unreliable messages is not guaranteed, with respect to either other unreliable messages, or reliable messages.
