### ISSUE TITLE
Access error

### ISSUE THREAD

**Issue by ZephyroalJC** [ValveSoftware/GameNetworkingSockets#54]
Hi there,

I'm just trying to build the sample(C/S demo in GameNetworkingSockets\examples) ,
but it turns out a access error when I'm trying to connect to server:
![image](https://user-images.githubusercontent.com/28585405/53866340-5462a380-402c-11e9-9e28-62f3f00a0f66.png)
Access exception when try to write into  0x0000000000000000
bool CCryptoKeyBase::GetRawDataAsStdString( std::string *pString ) const
{
	pString->clear();
	uint32 cbSize = GetRawData(nullptr);
...

IDE: VS2017 Community
Codebase: Latest commit on master
Thanks.

**Comment by fletcherdvalve** [comment]
Thanks.  I suspect this has something to do with mismatched compile / debug settings or something, with either protobuf or std::string.

**Comment by LWestling** [comment]
Is there any way to fix this? Currently, always crashing when calling ConnectByIPAddress.

**Comment by fletcherdvalve** [comment]
Can you confirm that your protobuf lib was compiled with the matching settings that you are using GameNetworkingSockets:

- static CRT / dynamic CRT
- debug / release

**Comment by netpyoung** [comment]
I also got same error (I tested using unity) - https://github.com/netpyoung/unity.gamenetworkingsockets/commit/c3747a8eb3d89e0da56f683d57769e2e07265cea

That is my environment for building Win64 version
* dynamic CRT
* i'm not sure is that default build option(`cmake -G Ninja ..`) is release or not. 
    - [buildscript](https://github.com/netpyoung/unity.gamenetworkingsockets/blob/master/Rakefile#L55)

Source 
- https://github.com/nxrighthere/ValveSockets-CSharp/commit/9c79a1eb42edece6c697347dca8dd9dd50f38cf9
- https://github.com/ValveSoftware/GameNetworkingSockets/commit/42d3ab872bff807ed83a772d82329ec4c5af854e
- protobuf: commit a4d93c235b16b10c97a70b35b5f824040199c9d6 (HEAD -> 3.5.x, origin/3.5.x)
- [Win64 OpenSSL v1.1.1c](https://slproweb.com/products/Win32OpenSSL.html)

**Comment by fletcherdvalve** [comment]
Gonna close this unless somebody can confirm there is an issue here.  I'm 95% sure this is just using libraries with mixed build settings.
