### ISSUE TITLE
Remove an unnecessary null pointer check

### ISSUE THREAD

**Issue by elfring** [ValveSoftware/GameNetworkingSockets#56]
[An extra null pointer check is not needed](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") in [the destructor for the class “CSteamNetworkListenSocketDirectUDP”](https://github.com/ValveSoftware/GameNetworkingSockets/blob/8b0c4dc8d9525bc797b3a0b32738d1d3c88b194e/src/steamnetworkingsockets/clientlib/steamnetworkingsockets_udp.cpp#L123 "Destructor for CSteamNetworkListenSocketDirectUDP").

**Comment by fletcherdvalve** [comment]
I do realize that this null check is not necessary.

However, since we are picking nits, I would like to point out that removing the check produces slightly inferior assembly.

https://compiler.uplinklabs.net/z/ncKLz7

**Comment by elfring** [comment]
Would another small source code improvement be nice also for affected software components?
