### ISSUE TITLE
OpenSSL version via Brew

### ISSUE THREAD

**Issue by kkukshtel** [ValveSoftware/GameNetworkingSockets#59]
Brew's command ```brew install openssl``` instals OpenSSL version 1.0.4. There should be a note in the docs that you need to force the install of 1.1 via ```openssl@1.1```.

Additionally, pkg-config needs to have it's path updated to find openssl by running this:
```export PKG_CONFIG_PATH="/usr/local/opt/openssl/lib/pkgconfig"```

Otherwise you'll get a ```Dependency libcrypto found: NO (tried cmake and framework)``` error.

**Comment by fletcherdvalve** [comment]
You wanna make a pull request?  Just so it goes in the right place and has the right context.  I don't know anything about OSX or Brew.

**Comment by kkukshtel** [comment]
Submitted a simple PR here https://github.com/ValveSoftware/GameNetworkingSockets/pull/60

**Comment by fletcherdvalve** [comment]
Merged, thanks!
