### ISSUE TITLE
May we please have a C# wrapper?

### ISSUE THREAD

**Issue by MostHated** [ValveSoftware/GameNetworkingSockets#7]
I want to start things off right and introduce myself. I am MostHated. I would like to request, please, that a C# wrapper be created so that us Unity users who are not the most amazing programmers in the world can still enjoy all the amazing Valve goodness.

**Comment by Vytek** [comment]
+1 for Unity

**Comment by igore34** [comment]
I never worked with Unity. But my understanding is that Unity has pretty similar transport layer under the hood (that is already integrated with their ECS etc). Just out of curiosity - what is wrong with Unity's system that make you people want to use Valve's sockets lib? 

I'm also assuming this will require a lot of extra work to integrate it with Unity's entities and not just C# bindings.

**Comment by RyouBakura** [comment]
@igore34 Unitys low level networking is closed source and they're veeery slow to fix broken things. Even a memory leak that was reported a few months back is still waiting to get fixed.

**Comment by pavelbraginskiy** [comment]
While C# bindings would be nice generally (not everyone using C# is using Unity), C# already has exemplary support for C++ interoperating. It wouldn't be hard to declare extern methods for the functions of the library you need to use and `DLLImport` them.

**Comment by AraHaan** [comment]
for c# put the library in an SafeNativeMethods class in an SafeNativeMethods.cs file and P/Invoke the library.

**Comment by mhsjlw** [comment]
This would be relatively simple to add through the use of SWIG-- although this project should transition to CMake first

**Comment by rlabrecque** [comment]
As soon as this is released in Steamworks, which it sounds like it will be in 1.43, I'll get it added to https://github.com/rlabrecque/Steamworks.NET, that should likely work nearly identically to the standalone version here with the exception of the PInvoke dll name.

**Comment by nxrighthere** [comment]
I wrote [C# bindings](https://gist.github.com/nxrighthere/fd43fdb0244a04db973755ead8fd6bfa) for basic functions, but the funniest thing is that the library works fine in native code, and only partially in .NET application. The initialization works fine, `GameNetworkingSockets_Init` returns true without any error, but it looks like `CreateListenSocket` doesn't work. Did I make a mistake somewhere? @rlabrecque

**Comment by rlabrecque** [comment]
What happens when you call CreateListenSocket? That actually looks pretty good!

**Comment by nxrighthere** [comment]
`CreateListenSocket` always returns `HSteamListenSocket = 1647690432` for the server and client. `GetListenSocketInfo` doesn't return `pnIP` and `pnPort` for some reason.

@tycho @fletcherdvalve Any thoughts guys?"

**Comment by fletcherdvalve** [comment]
I don't know anything about C# interop, sorry.

**Comment by rlabrecque** [comment]
Found the problem, your EntryPoint's are almost all wrong, copy/paste error :) So 1647690432 is just the address that SteamNetworkingSockets() is returning. Do I still use EntryPoint in Steamworks .NET? I think I got rid of it, or at least thought of getting rid of it for reasons like this, it's just unnecessary duplication which leads to problems like this.

```
		[DllImport(nativeLibrary, EntryPoint = "SteamNetworkingSockets", CallingConvention = CallingConvention.Cdecl)]
		public static extern HSteamListenSocket CreateListenSocket(int nSteamConnectVirtualPort, uint nIP, ushort nPort);
```

**Comment by nxrighthere** [comment]
How EntryPoint's can be wrong if I clearly see them in the DLL?

![EntyPoints](https://i.imgur.com/r4bZ20h.png)

It's obvious that the functionality is behind them because EntryPointNotFoundException is throwing. I double checked everything, functions itself works fine.

**Comment by nxrighthere** [comment]
The only thing that comes to my mind is that `ISteamNetworkingSockets` interface should be implemented in C# bindings to execute these functions properly. Or as an option write the native proxy that processing callbacks and returns stuff to the managed side.

**Comment by rlabrecque** [comment]
You're just using the SteamNetworkingSockets entrypoint everywhere, except for the first two functions.

Like CreateListenSocket needs `EntryPoint = "CreateListenSocket"`, but it currently has `EntryPoint = "SteamNetworkingSockets"`

**Comment by nxrighthere** [comment]
Do you understand what you are suggesting, and why it's not working for this library? It's not the Steam API where the all functions are globally accessible. In this library, there is only six global accessor. At least, please, just take a look at the [source code](https://github.com/ValveSoftware/GameNetworkingSockets/blob/master/include/steamnetworkingsockets/isteamnetworkingsockets.h#L367).

**Comment by pipliz** [comment]
Disclaimer: I don't write/do a lot with c/c++.

I don't see how one could make a working C# wrapper for this library as-is. It's based around that 1 method which returns a C++ class with lots of virtual functions. I don't think you can PInvoke into 
 (virtual) c++ class functions. You'd have to somehow marshal the class layout, which isn't (cross compiler / platform) defined for c++.

There'd need to be an explicit C export wrapping the class functions by passing a pointer to the class and calling the desired function. Probably together with explicit constructor & destructor exports.

Though to be fair, I'd guess that's required to use this library properly in C as well.

**Comment by nxrighthere** [comment]
Exactly. I think the best way to solve this issue is to make an EntryPoint for each native function. At least, this is how it's done in other libraries.

**Comment by fletcherdvalve** [comment]
Yeah the Steamworks SDK has a "flattened" version where all the entry points are plain functions, not virtual methods.  We should add a flat interface to make it easier to bind to other languages.

There *are* legit reasons for the "get a pointer to an interface" idiom.  It isn't really useful in this case where you are binding directly to a specific version of the interface and statically linking, and you don't have two different potential "identities" (a "client" and "gameserver" -- that's a weird Steam thing.)

**Comment by nxrighthere** [comment]
> I see what you mean, but my point still stands that you're merely getting the initial entry point. 

Yeah, that's true. All these functions return the same number.

> You could try implementing it like this: rlabrecque/Steamworks.NET@e217e9b

Nah, I'm tired of this for now. 😆

**Comment by rlabrecque** [comment]
> Nah, I'm tired of this for now. 😆

Yeah, I also wouldn't recommend it. 🙃

**Comment by fletcherdvalve** [comment]
Now that the flat interface has been written, anybody want to take a stab at the C# wrapper?

**Comment by nxrighthere** [comment]
Yep, I'll try to do it now.

**Comment by nxrighthere** [comment]
Still doesn't work for me. `SteamNetworkingSockets_CreateListenSocket` return `2147500035`, and `SteamNetworkingSockets_ConnectByIPv4Address` return `2`.

**Comment by nxrighthere** [comment]
Callbacks are not firing, and `SteamNetworkingSockets_GetListenSocketInfo` return zero for both `pnIP` and `pnPort`.

**Comment by Salty-Sailor** [comment]
I am trying to build a C# wrapper too, and I have met the similar problems about **Callbacks**. During the **connection_test.cpp** example, you do some work in the **g_Callbacks** such as AcceptConnection , change the connection state(connecting -> connected),  And if I want to do the same thing on C# side, I should have to do things like:
Step_1.Implement a **FSteamNetConnectionStatusChangedCallback** type callback in C# side 
Step_2.call **SteamNetworkingSockets_RunConnectionStatusChangedCallbacks** in some suitable places.

But I am not sure if it is possible to marshal a **FSteamNetConnectionStatusChangedCallback** type func pointer in C# side (**or if someone knows how to do this please tell me!!!!!**). So I guess that I have to write my self-define callback function in c++ and add interface so I can invoke the callbacks on C# side, but this work flow seems a little bit strange. I thought my callback functions should totally be written in C# but not in the libGameNetworkingSockets.dll.

Any one has some suggestions?

**Comment by AraHaan** [comment]
Maybe one can use c++ /clr to and somehow display the types and functions of the library using that. I used that before in .NET when nothing else worked for me on something I thought was simple.

**Comment by nxrighthere** [comment]
Yes, the native proxy is what I talking about earlier, but it's an ugly way to solve this... 😞

**Comment by fletcherdvalve** [comment]
@tycho Has pointed out a bunch of flaws in the first attempt at a flat interface.  We'll take another stab at it.

**Comment by fletcherdvalve** [comment]
@nxrighthere I've updated the flat interface.  Could we take another look at getting this working?  what problems were you seeing?

**Comment by Oneluv17** [comment]
I hope it ALL about fixed.. So..most of my mental issues will get easier..
My X.. Turned me.. Into a.. X-box?

**Comment by nxrighthere** [comment]
@fletcherdvalve Sorry, I'm very busy these days and don't have time for this, unfortunately.

The problem was with the server. It's never started (`SteamNetworkingSockets_GetListenSocketInfo` was always return zero for `pnIP ` and `pnPort`) and callbacks was not firing.

**Comment by kkukshtel** [comment]
Is there work being publicly done on a C# interface? Would love to possibly contribute.

**Comment by fletcherdvalve** [comment]
@kkukshtel DO IT!  Let me know if the flat interface is missing anything.

**Comment by kkukshtel** [comment]
@fletcherdvalve Is there any documentation on how the library is intended to be used besides the test file?

**Comment by kharder** [comment]
What @rikimaru0345 said :)

**Comment by nxrighthere** [comment]
@fletcherdvalve The fixed flat interface seems good now, except only one thing. Each function requires pointer `intptr_t instancePtr` to the `ISteamNetworkingSockets` which should be implemented on the managed side as I mentioned in [this](https://github.com/ValveSoftware/GameNetworkingSockets/issues/7#issuecomment-379369478) comment. Without this callback interface, nothing is going to work. 

There are three options:

1. Implement callback interface on the managed side and marshal pointer to feed it to the flat interface.
2. Create a tiny native proxy for this interface which will process stuff and trigger callbacks without implementation of the interface itself on the managed side. This requires to wrap another DLL.
3. Implement dispatcher around this interface directly in the library which will return a pointer to the interface itself that can be stored on the managed side and used with the flat interface.

This is the only thing that separates me from the release of the C# wrapper.

**Comment by nxrighthere** [comment]
@fletcherdvalve I have good news and bad news...

The good news is that the fixed flat interface seems to works fine, thank you. I've made a basic wrapper, and it works.

The bad news is that I encountered some problems with the library. I've tried to perform stress test without sending any messages: 

![valvesockets](https://user-images.githubusercontent.com/8279330/45419883-f74feb80-b6a1-11e8-825a-5ce258271663.png)

As you can see here, only 70 simulated clients was successfully connected. I've captured 30,000 packets on loopback and here's what I got:

![loopback](https://user-images.githubusercontent.com/8279330/45419635-477a7e00-b6a1-11e8-8d51-8af04a0cb9ad.PNG)
![loopback2](https://user-images.githubusercontent.com/8279330/45420026-76ddba80-b6a2-11e8-884b-b9ac9f97b3b9.PNG)

If you want, I can send you everything you need for further investigation.

**Comment by nxrighthere** [comment]
With only a few clients everything works fine. I think this issue is related to the burst of new incoming connection (deadlock?).

**Comment by nxrighthere** [comment]
Also, `CSteamNetworkingMessage::Delete` should be wrapped in the flat interface for destroying received messages via release pointer.

**Comment by AraHaan** [comment]
I am not sure about the underlying implementation of the wrapper but why would it be deadlocking? is it run on the main thread or something? Why not use ``Task``s then from C#'s ``TaskFactory`` in ``System.Threading.Tasks.Task.Factory`` if it is?

**Comment by nxrighthere** [comment]
The problem not with the wrapper, problem with the native library itself.

**Comment by nxrighthere** [comment]
The native library is full of `SteamDatagramTransportLock` _recursive_timed_mutex_ in nutshell. In almost every single function.

**Comment by AraHaan** [comment]
oh I see.

**Comment by kkukshtel** [comment]
Omg yes this is amazing!! Thank you so much. I’ll see if I can contribute
in any way.

**Comment by fletcherdvalve** [comment]
@nxrighthere Thanks for this help!  I'll add a flat wrapper to release a message, and look into the deadlock thing you mentioned.

**Comment by SradnickDev** [comment]
@nxrighthere Thank you! This is amazing!

**Comment by nxrighthere** [comment]
Work on an [API reference](https://github.com/nxrighthere/ValveSockets-CSharp#api-reference) has been completed. Any technical or grammar fixes are welcome.

**Comment by fletcherdvalve** [comment]
I added a link to @nxrighthere's project.

We don't really have expertise doing this, so I don't think this is something we would implement ourselves.

**Comment by nxrighthere** [comment]
The wrapper updated to the latest version up to https://github.com/ValveSoftware/GameNetworkingSockets/commit/c4a97732fd6cad7f146d51a6f674ab705719f4d0 commit. API reference is under construction.

**Comment by nxrighthere** [comment]
The wrapper and API reference are updated up to 2d2001f commit.

**Comment by fletcherdvalve** [comment]
I've tagged an official v1.1 release, if you want to pin it to that.
