### ISSUE TITLE
Missing flat interface in the Steamworks SDK

### ISSUE THREAD

**Issue by helloer** [ValveSoftware/GameNetworkingSockets#70]
Are there any plans to expose flattened interface for IGameNetworkingSockets in the Steamworks SDK like it has been done in open-source version? Is there any ETA for this?

**Comment by Frooxius** [comment]
+1 for this! I would like to use the Steamworks version from C# (given that this is still missing some 
features like the NAT piercing), but currently I don't know of any good wrappers (the Steamworks.NET is still stuck on 1.43 version).

Being able to use the https://github.com/nxrighthere/ValveSockets-CSharp with the Steamworks version would help greatly.

**Comment by rlabrecque** [comment]
I was looking at support for IGameNetworkingSockets in Steamworks .NET, and I believe this is blocking it.

**Comment by rlabrecque** [comment]
I'll have a deeper look into those questions this weekend 👍

**Comment by helloer** [comment]
@fletcherdvalve I have not found any issues with the flat interface, we really need this in the Steamworks SDK as it blocks our release.

**Comment by fletcherdvalve** [comment]
OK, thanks.  I'll make sure the next SDK release has a matching flat interface.

**Comment by fletcherdvalve** [comment]
I've updated the Steamworks SDK.  The flat interface has had a pretty big overhaul.  And the missing interfaces (and structs, too!) are now present.

I'm working with the guys at steamworks.net and facepunch to make sure it is easy for them to write a wrapper for this API and the rest of the steamworks SDK.

I will close this bug when the flat API here is updated to match the one in Steamworks exactly.

**Comment by fletcherdvalve** [comment]
I've updated the flat interface here to match Steamworks SDK 1.48.

let me know if there are issues with either flat interface.
