### ISSUE TITLE
Cross Compiling Mingw from Linux

### ISSUE THREAD

**Issue by SnapperTT** [ValveSoftware/GameNetworkingSockets#72]
I've been attempting to build this from Linux targeting Windows without much success.

Has anyone been able to successfully do this? All of the dependencies build fine.

Procedure for building is currently:
1. wget the latest stable from github
2. untar it
3. make a subdirectoy called `deps_protobuf`, cd into it, and build protobuf with mingw:
`
./configure --build=x86_64-pc-linux --host=x86_64-w64-mingw32 && make
`
This builds without issue
4. make a subdirectory called `deps_openssl`, cd into it, and build openssl with mingw:
`./Configure --cross-compile-prefix=x86_64-w64-mingw32- mingw64 && make`
This builds without issue
5. Invoke cmake for GameNetworkingSockets:
`cmake -G "Unix Makefiles" --verbose=1 -DProtobuf_LIBRARIES=../deps_protobuf/libprotobuf.dll -DProtobuf_INCLUDE_DIR=../deps_protobuf/src/ -DOPENSSL_FOUND=true -DOPENSSL_ROOT_DIR=../deps_openssl/ -DOPENSSL_SSL_LIBRARY=../deps_openssl/ -DOPENSSL_CRYPTO_LIBRARY=../deps_openssl/crypto/ -DOPENSSL_INCLUDE_DIR=../deps_openssl/include/ -DCMAKE_TOOLCHAIN_FILE=path/to/cmake_toolchains/cmake-win64`

Cmake is happy with protobuf, but fails to detect OpenSSL. Here is the output:

```
-- The C compiler identification is GNU 9.1.0
-- The CXX compiler identification is GNU 9.1.0
-- Check for working C compiler: /usr/bin/x86_64-w64-mingw32-gcc
-- Check for working C compiler: /usr/bin/x86_64-w64-mingw32-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/x86_64-w64-mingw32-g++
-- Check for working CXX compiler: /usr/bin/x86_64-w64-mingw32-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting build type to 'RelWithDebInfo' as none was specified.
-- Looking for BCryptEncrypt
-- Looking for BCryptEncrypt - found
-- Found Protobuf: ../deps_protobuf/libprotobuf.dll (found version "3.7.0") 
CMake Error at /usr/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY) (found
  version "1.1.1c")
Call Stack (most recent call first):
  /usr/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.15/Modules/FindOpenSSL.cmake:413 (find_package_handle_standard_args)
  src/CMakeLists.txt:8 (find_package)
```
What's really cryptic is that its claiming that OPENSSL_CRYPTO_LIBRARY is missing despite being explicitly defined and it also claiming that its found version 1.1.1c (?).

If I edit src/CMakeLists.txt and disable the openssl check it finishes configuring and starts to compile and stops when it hits an openssl dependency. So this appears to be the only thing holding back a mingw cross compile.

**Comment by SnapperTT** [comment]
I was able to fix this by switching to bcrypt and making a small edit to the source.

Switching to bcrypt:
`cmake -G 'Unix Makefiles' -DUSE_BCRYPT=true -DProtobuf_LIBRARIES=/full/path/to/extlib/steamGameNetworkingSockets/build/../deps_protobuf/libprotobuf.dll -DProtobuf_INCLUDE_DIR=../deps_protobuf/src/ -DCMAKE_TOOLCHAIN_FILE=path/to/cmake_toolchains/cmake-win64 ..`

This had the additional benefit of removing the openssl dep.

The edit to the source is case-sensitivity change:
`#include <Bcrypt.h>` -> `#include <bcrypt.h>` in `src/common/crypto_bcrypt.cpp`

This can be fixed in the general case with a __has_include guard:
```
#if __has_include(<Bcrypt.h>)
	#include <Bcrypt.h>
#else
	#include <bcrypt.h>
#endif
```

**Comment by SnapperTT** [comment]
I've briefly attempted to cross compile Linux -> Osx with osxcross and have ran into the same issue regarding openssl. Has anyone manged this with any degree of success?

**Comment by tycho** [comment]
I got it cross-compiling for MinGW on Linux after 87747e499b0f5da17a07cc47ca1e7b7fbaf6c264. The include filenames are only case-sensitive on Linux, so we might as well just normalize to that, even though Microsoft throws upper case letters in their filenames sometimes.

**Comment by fletcherdvalve** [comment]
I think this is resolved then?  @SnapperTT reopen if you still have issues
