### ISSUE TITLE
C++ version ?

### ISSUE THREAD

**Issue by yamashi** [ValveSoftware/GameNetworkingSockets#75]
Hello,

I was wondering what was the C++ target version ? Or if there is a list of compilers to support ?

Best,
Max

**Comment by fletcherdvalve** [comment]
C++11 is required to compile the lib.  I don't really know what particular versions of GCC / Clang / MSVC this implies, to be honest.

I don't think C++11 is required to link with or use the lib.

If you look at the travis continuous integration, you can get a list of the environments and compilers we're currently testing on.

@tycho May know off the top of his head.

**Comment by tycho** [comment]
C++11 has been broadly supported for a while now, and we definitely recommend using the **newest stable compiler versions you can**.

But if you're forced to use something older, here are the bare minimum compiler versions for C++11 support (though this doesn't guarantee that it will be usable, as we haven't tested it):

- Clang 3.3
- GCC 4.8.1
- Visual Studio 2015
- Intel C++ Compiler 15
