### ISSUE TITLE
Valve 25519 implementation fails when targeting 32 bits

### ISSUE THREAD

**Issue by yamashi** [ValveSoftware/GameNetworkingSockets#76]
Hello,

When running the library without OpenSSL's 25519 implementation and using valve's implementation will result in an error when connecting server side in
`bool CECSigningPublicKey::VerifySignature( const void *pData, size_t cbData, const CryptoSignature_t &signature ) const`

To reproduce simply build the examples in 32 bits with the defines to toggle Valve's implementation.

**Comment by fletcherdvalve** [comment]
What platform / OS is this?  We use that code in Steam on 32 bit windows, so I know it isn't totally broken.
