### ISSUE TITLE
Lifetime stats of a connection

### ISSUE THREAD

**Issue by HiddenMonk** [ValveSoftware/GameNetworkingSockets#77]
Currently through steams api and the flat api we can GetQuickConnectionStatus which has info such as inPacketsPerSec and inBytesPerSec.
Could we have a GetLifetimeConnectionStatus that has info such as inTotalPackets and inTotalBytes. It seems that data is already being calculated and stored anyways, so it would be nice to access it through steams api since then we have a way of tracking how many packets are waiting to be read by us by doing inTotalPackets - totalPacketsRead (totalPacketsRead is something we would handle ourselves after calling ReceiveMessagesOnConnection).

**Comment by fletcherdvalve** [comment]
I have been pretty hesitant to add this to the API, at least the Steam API, because once it is released as part of the Steamworks SDK, that exact ABI must be supported essentially indefinitely.  it adds a big maintenance burden, so the value of adding it must be really high.  Something as simple as adding a member to a struct has to be done carefully.  And this sort of API, I totally expect there to be lots of changes, and so I think the cost/benefit is not there.

That's why the public API I have just prints a bunch of info.  So if it's just for diagnostic purposes, does the text API suffice?

(I'm referring to GetDetailedConnectionStatus)

**Comment by HiddenMonk** [comment]
Ah I understand =).
I think I have a workaround for my needs, I basically just wanted to make sure the receiving buffer of a connection doesnt somehow grow until running out of memory, such as only reading x number of packets a frame or second, but someone sending way more than what is expected (ddos?).
My workaround is to just detect if I have reached the max allowed packets read a frame, multiple times in a row like 1,000 times in a row, just as a safety. I am no pro at this, so I may be going about this wrong, just trying to prevent malicious peers in a peer to peer game from causing issues.

**Comment by fletcherdvalve** [comment]
Right now there is a configuration option, k_ESteamNetworkingConfig_SendBufferSize.  It seems like what you really want is a max receive buffer size.  When the limit is exceeded, the receiver could either drop packets with new data (but continue to send keepalives, etc), or it could terminate the connection.

**Comment by HiddenMonk** [comment]
Exactly, when the receive buffer is full it should terminate or give some warning for me to act on. However, when looking at the code it seemed like there was no collection for the received messages, but more so a node based system or something where each message has a reference to its parent or child or something. So I didnt ask for a max receive buffer size since I didnt think the code was setup for it.

**Comment by fletcherdvalve** [comment]
Right, there isn't a single big buffer that holds everything.  But we could put limits on the total memory usage.

**Comment by HiddenMonk** [comment]
Awesome =), control over max memory usage and such can be great for safety. In a normal environment it might not be needed, but Im just thinking more so about malicious users. However, dont feel rushed to implement this since the workaround should be fine for now.
From memory, steam lobbies chat messages also suffer the same issue, even worse since reading the messages doesnt remove it from the buffer, only leaving the lobby clears it.
