### ISSUE TITLE
Peek ahead into reliable stream?

### ISSUE THREAD

**Issue by muchcharles** [ValveSoftware/GameNetworkingSockets#78]
I saw the reliable stream supports message boundaries within.  Is it possible to peek ahead into the reliable stream during packet loss?

For instance when sending game inputs for a deterministic game, it can have a flag if the previous inputs are the same as the current.  If input message A B and C are sent, and packetloss interrupts B, C could have a flag saying the inputs in B were the same as C and we could fill in the gap without retransmission delay.  Are out of order messages after loss (or just delivered out of order) able to be read-ahead in some way like that?

**Comment by fletcherdvalve** [comment]
I'd need to review the wire format protocol closely, but I don't think that it's possible to look ahead in the stream.  You cannot just jump ahead and interpret random bytes.  But even if it is possible right now, what if there is a subtle change to the format that made it impossible.  Then we have to trade off making that wire format change against breaking this feature.  I don't think the potential use cases, while having some value in some cases, are useful enough to justify the complexity, design constraints, and maintenance burden.
