### ISSUE TITLE
Java / Python bindings

### ISSUE THREAD

**Issue by kmare** [ValveSoftware/GameNetworkingSockets#8]
First of all, thank you for releasing the library as open source!
Are there any plans implementing Java and/or Python bindings?

**Comment by smekras** [comment]
I'm interested in Python bindings as well.

**Comment by Cazadorro** [comment]
If its opensource, you can do that yourself...

**Comment by kmare** [comment]
@Cazadorro Yes, it is open source. I wish I had the time to do it myself now. But at the very least I could help with testing if someone would get it started.
Thanks for the useful comment though.

**Comment by AraHaan** [comment]
Python is easy, just wrap the code into an Python PyTypeObject struct and make an class using it’s C API. I even know their C API and I made quite a few packages using c for python. Just that you would need to use distutils to compile. You can use the same approach as C in c++ or you can use boost.python however it adds useless bloat so I recommend using Python.h and all of their stuff directly as if you are writing it in C.

So yeah it does not need an complete rewrite. Just make the implementation in c extension modules and publish it to pypi (python package index).

**Comment by fletcherdvalve** [comment]
Anybody want to write this and submit a pull request?

I just added a plain C interface that might make it easier.

**Comment by fletcherdvalve** [comment]
I'm going to go ahead and close this issue.  This is not something we have expertise to do.  If somebody wants to write a good Java/Python wrapper on top of the plain C API, we will add a link to it in the readme so people can find it.
