### ISSUE TITLE
More than 1 instance of GNS (ISteamNetworkingSockets*) on the very same application

### ISSUE THREAD

**Issue by Levendo** [ValveSoftware/GameNetworkingSockets#80]
We have 2 basic states in our game. Lobby and match. They both use GNS. Actually we destroy the GNS library instance before switching to match state from lobby and create new one for match. Everything is okay. But i'm still super curious about if we want to have a service that covers both states and needs socketing concurrently.

How about of a lobby client socketing and a match client socketing should be working concurrently? as they have connections to their own servers. Lobby and Match servers. In other words the very same client can connect to the lobby server and can also connect to the match server.

 As long as i noticed it is quite impossible for GNS to handle this strange situation as it uses a singleton instance which is created at "GameNetworkingSockets_Init" interface.

So what i did was to create a new interface which creates a new ISteamNetworkingSockets for each call and also has a kill method. In other words, no more singleton creation, it creates a new instance per new create interface. (and also has similar kill method) Now instances should be controlled from outside the library.

I did tried and it worked quite nice. As long as i don't have the overall experience of GNS source code, i'm not %100 sure about if this may fail somewhere. Could you please enlighten me about how this affects the mechanics of the library? Does it support it or? Thank you very much.

**Comment by fletcherdvalve** [comment]
Sorry for the extremely late reply.

The idea behind the ability to create more than one instance is _primarily_ the ability to give each interface a different identity.  This is actually a holdover from the steamworks SDK, which has a user and you can also have a single "gameserver" interface logged into Steam.  That's where the whole notion of more than one interface comes from.  In Steam this is often used for "listen servers", meaning one player is hosting the game server.  Remote clients can send messages to either the user or the gameserver, they are two separate entities.

Each interface also have a separate queues for callbacks and you can set connection options tehre (which are inherited).

There is no current mechanism to create additional interfaces in the library ad hoc, but it could certainly be done.
