### ISSUE TITLE
Include .so and .dll in the package when releasing new versions

### ISSUE THREAD

**Issue by gtnardy** [ValveSoftware/GameNetworkingSockets#81]
Hey there, this lib is awesome, the only problem is the need for the compilation. It would be awesome if you included the .dll's and .so's in the future releases.

**Comment by Levendo** [comment]
I believe it is not a good idea to put the pre-builds, as long as there are many options for compilers to build for. Nice thing source is supporting many compilers so platforms. You may check "minbase_decls.h". We managed to build for iOS, Android, PC and Linux.

**Comment by gtnardy** [comment]
> 
> 
> I believe it is not a good idea to put the pre-builds, as long as there are many options for compilers to build for. Nice thing source is supporting many compilers so platforms. You may check "minbase_decls.h". We managed to build for iOS, Android, PC and Linux platforms.

I see, I just think that releasing some pre-builds would make it easier for some people and encourage them to use the framework, as we are skipping some barriers of having to install and download several prerequisites, even more for Windows builds.
