### ISSUE TITLE
Impossible to implement STUN on a listen socket?

### ISSUE THREAD

**Issue by eddiejames** [ValveSoftware/GameNetworkingSockets#83]
I could easily be missing something, but I don't see how to use STUN (or similar) to get my public IP on a listen socket. The library doesn't allow me to start an outbound connection from a listen socket, therefore I cannot ping a STUN server. If I start a new connection to do so, I'll get my public IP with the incorrect port. And I cannot simply then use the local port number of the listen socket because the NAT may map it differently. Any suggestions? The readme suggests this is possible?

I did see https://github.com/ValveSoftware/GameNetworkingSockets/issues/64 but that's for in-library implementation I think?

**Comment by fletcherdvalve** [comment]
Yeah, I am interested in making something relatively high level and turnkey (get it!?!?) right now.  I don't think it's possible to manually put STUN/TURN in front and then somehow pass it off to this layer. 
 I don't know when this will rise in priority to actually get implemented.  Hopefully this year. :(

**Comment by eddiejames** [comment]
No problem, thanks for letting me know. I did manage to implement it with some pretty rough hacks: https://github.com/eddiejames/GameNetworkingSockets/tree/dev

Obviously not ideal, but it is functional if anyone else needs it ASAP and doesn't mind the mess.
