### ISSUE TITLE
SteamNetworkingSockets Crash - Reproducible

### ISSUE THREAD

**Issue by HiddenMonk** [ValveSoftware/GameNetworkingSockets#89]
This is using the NetworkingSockets in the steam SDK, using a c# wrapper.
I posted the issue on the steamworks forum https://steamcommunity.com/groups/steamworks/discussions/0/1736633446487804212/, but its prob better to have it here.

Using SteamNetworkingSockets
Sending a p2p connection request through steams relays to someone who doesnt have a listen socket open,
will still receive a ConnectionStatusCallback with state set to Connecting and socket handle set to 0. However, no more callbacks are given. (Usually I get another callback with state as Connecting and socket handle as 65536 in my cases in normal situation)
At this point, if you try to close that connection, your game will crash.
Also, even if you just ignore it, when you close the game and shutdown the steam api, you will also crash since it probably tries to close that connection behind the scenes.

To be clear, the person who doesnt have a listen socket open will receive a callback and be the one crashing later. The person doing the sending seems to handle things fine and just receives a Misc_Timeout callback later.

I would have assumed if you have no listen socket open that you would not receive anything, let alone crash from it being some kind of bugged state connection that cant close D=.
I am using a C# wrapper around the steamnetworkingsockets, but I dont think that would matter in this case.
(I am using something like this if it matters https://github.com/OndrejPetrzilka/Steamworks.NET/tree/SteamNetworkingSockets)

The reason I feel it isnt something to do with my code is because I loaded up the Facepunch steamworks test for unity here https://github.com/Facepunch/Facepunch.Steamworks.UnityTest and it caused crashes as well.

**Comment by HiddenMonk** [comment]
Here is a repro build and source for unity. The build is in the Builds -> Test folder

[CrashTest-Facepunch.Steamworks.UnityTest-master.zip](https://github.com/ValveSoftware/GameNetworkingSockets/files/4009969/CrashTest-Facepunch.Steamworks.UnityTest-master.zip)

This was the code

```
using UnityEngine;
using Steamworks;
using Steamworks.Data;
using UnityEngine.UI;

public class TestNet : MonoBehaviour
{
	public InputField sendToSteamID;
	public Button sendButton;

	void Awake()
	{
		sendButton.onClick.AddListener(OnSendButton);

		SteamClient.Init(480);

		SteamNetworkingSockets.ConnectRelay<ConnectionInterface>(76561198835511111); //Just some radom connection attempt so facepunch initializes things.
		SteamNetworkingSockets.OnConnectionStatusChanged += OnChange;
	}

	void OnChange(Connection c, ConnectionInfo i)
	{
		Debug.Log(c.ConnectionName + " " + i.SteamId + " " + i.State);
	}

	void OnSendButton()
	{
		ulong steamID = 0;
		if(ulong.TryParse(sendToSteamID.text, out steamID))
		{
			Debug.Log("Sending connection request to steamID:" + steamID);
			SteamNetworkingSockets.ConnectRelay<ConnectionInterface>(steamID);
		}else{
			Debug.Log("Failed to parse steamID.");
		}
	}
}
```

Here is a video https://www.youtube.com/watch?v=HxJQ9pplLRQ

**Comment by fletcherdvalve** [comment]
Thanks for this report.  I am checking it out now.  I _think_ that this is fixed in a client beta that is shipping soon.  There were some bugs in the P2P codepath when connections failed very early, and this sounds a lot like that.

**Comment by HiddenMonk** [comment]
Thanks for looking into it =). Let me know when you think its fixed and I'll re-test it. When the  new client is shipped, would I need to grab a new steamworks sdk dll or anything, or should I just test with everything as is?

**Comment by fletcherdvalve** [comment]
Probably to retest, just make sure you are opted into the Steam client beta, and the quit and restart and make sure it updates, and try to reproduce.

I'll comment here again when the beta is updated.

**Comment by HiddenMonk** [comment]
kk sounds good =)

**Comment by fletcherdvalve** [comment]
A new Steam client was just released that has the code changes that I believe will fix this crash.  let me know.

https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/1698353956261271592

**Comment by HiddenMonk** [comment]
thanks! I will do some tests now with the beta client.

**Comment by HiddenMonk** [comment]
Looks like its fixed =). I am not crashing, and I am not even receiving any connection attempt messages, which is good.
Thank you!
