### ISSUE TITLE
Building readme clarification

### ISSUE THREAD

**Issue by silentbaws** [ValveSoftware/GameNetworkingSockets#90]
For the visual studio building instructions for protobuf this cmake command is used
`C:\dev\protobuf\cmake_build> cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -Dprotobuf_BUILD_TESTS=OFF -Dprotobuf_BUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=c:\sdk\protobuf-amd64 ..\cmake`

And for GameNetworkingSockets cmake this command is used
`cmake -G Ninja ..`

Not sure if this is just an issue with my setup but this caused a whole bunch of errors and had to use this command for the GameNetworkingSockets cmake to get it working
`cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ..`

So not sure if this is an issue for anyone else but if it is it might be good to update the building instructions.

**Comment by fletcherdvalve** [comment]
You wanna prepare a pull request?

**Comment by fletcherdvalve** [comment]
Fixed by 54139bb01ad964066eafbc5fddfa32008fa19d04
