### ISSUE TITLE
incoming + outgoing on the same interface

### ISSUE THREAD

**Issue by sidhujag** [ValveSoftware/GameNetworkingSockets#91]
Great work on the open source side of things!
I forked and created a gateway example specific to the Syscoin cryptocurrency network for UDP propogation of mempool transaction packets to help with the real-time double-spend detection of ZDAG (our point-of-sale crypto currency algorithm). I needed a high throughput UDP propogation for messages, without verification (just hash dedup's was enough). You can find my work here: https://github.com/syscoin/GameNetworkingSockets/blob/master/gateway/gateway.cpp#L229

I noticed that if I used the global interface that you created in GNS library I get call backs on the client as a server, it seems that the callbacks get confused and then the GatewayServer incoming messages don't pick up the actual request and times out, I get the "AssertMsg( false, "Application didn't accept or close incoming connection in a reasonable amount of time.  This is probably a bug." );" message leading me to believe either I'm not setting up the callbacks properly or that the interface is incompatible with incoming and outgoing at the same time (being the same IP doesn't matter).

I created a network to illustrate the error:

From gateway A I set outgoing to gateway B and from B I set outgoign to gateway C and from C I set outgoing back to A and A throws up soon as C tries to /connect because the client poller gets the message instead of the server for some reason. This led me to believe that each outgoing client and server needed its own ISteamNetworkingSockets interface which handles its own message queue (on the server it handles child connections, but incoming and outgoing connections don't confuse the interface): https://github.com/syscoin/GameNetworkingSockets/blob/master/src/steamnetworkingsockets/clientlib/csteamnetworkingsockets.cpp#L1598

So I actually return the new interface from GameNetworkingSockets_Init() and take care of deleting the object (had to add virtual Destroy() to the base class so Destroy() can be called on the interface as well), this way my outgoing GatewayClient's all have their own interface, and the server creates one (GatewayServer) to manage incoming connections, which does work.. so question is, is it a bug in the internal guts which causes confusion between interface reuse between listening/outgoing connections or is the pattern I'm using wrong or is the right way to have the application manage their own interface and take care of destroying it when they are done? If having your own interface makes sense I can PR that in.

Thanks!

**Comment by fletcherdvalve** [comment]
Sorry, I honestly am not sure what the bug is here, and this issue is really old.  Reopen it if there is something you think I need to fix.
