### ISSUE TITLE
Support Linking with Steamworks SDK

### ISSUE THREAD

**Issue by h3xcat** [ValveSoftware/GameNetworkingSockets#93]
I was unable to compile the example code using the Steamworks SDK. I'm getting `Shouldn't be including this!` error, generated by `steamnetworkingsockets.h(20)`. I tried bypassing the check with `#define STEAMNETWORKINGSOCKETS_PARTNER` which gave me a bunch of syntax errors.

**Comment by fletcherdvalve** [comment]
If you are linking with the Steamworks SDK, you shouldn't use this code.  You should use the version provided by the SDK.

Can you describe the reason you do not want to just use the interfaces provided by the SDK?

**Comment by h3xcat** [comment]
I'd like to run SDK optionally for things like ingame overlay, and have a fallback when Steam is not running, maintaining networking support. Since the SDK and GameNetworkingSockets share the same header names, I'm unable to link them together in the same executable.

**Comment by fletcherdvalve** [comment]
Gotcha.

Well, what you describe is exactly what CSGO and Dota do. :) Actually Dota can switch between using Steam or the standalone lib using a command line switch.  So it is possible, we just do some hackery in the version of the header we use.  I will look into making the official header have this hackery.  There are some Steam partners who also would like to run in this way, so you are not the only person asking for it.

I have updated the title and marked it as a feature request.

**Comment by fletcherdvalve** [comment]
OK, I've made it so that the public symbols exported by the standalone lib do not conflict with those exported by steam_api.dll. 
 You still need to do some hackery to the header to be able to call them both -- but they do have different names.  I don't want to complicate the header any further with more #defines for niche use cases to fix this -- the header already has enough such #defines.  I think this is the right tradeoff.

**Comment by fletcherdvalve** [comment]
952a7b95cedef1c097b811a7a381af8b0871d768 significantly improves this situation.  It is now really easy to add support for linking with either Steamworks or the opensource code, and switching back and forth, even at runtime.
