### ISSUE TITLE
Maybe an odd question, but, is there a keepalive time for a game server?

### ISSUE THREAD

**Issue by Levendo** [ValveSoftware/GameNetworkingSockets#96]
We have a game servers consisting of lobby and matches. They both use GNS. Anyway, we want our lobby servers keep alive as possible as we can. So it is like ~150 client connections per few minutes per lobby server connecting, do some stuff and disconnect. Standart lobby server/s. No big deal as they are many. They are dockerized apps. Problem is literally this; after 15 hours of a lobby server is initialized and run, it disconnects all of its clients and voila, no connections. We did many tests and this 15 hours is quite common instead of how many connections established or not in that interval. Do we have any config to set a game server's life time or something like that? Thank you very much.

**Comment by fletcherdvalve** [comment]
I'm going to need more information.  When any disconnection happens, there are reason codes and such.  What reason codes do the client and server see when this happens?

Is there any debug output?

**Comment by fletcherdvalve** [comment]
To answer the question - there is no keepalive time for a process and nothing that I can think of that happens at 15 hours.

**Comment by Levendo** [comment]
Thanks for the fast reply. We are on something else now which is quite urgent. I will inspect it more later, It is probably something else but whatever the reason, i will let you know. Thank you again. GNS is wonderful.

**Comment by fletcherdvalve** [comment]
Closing this.  Re-open it if you find out there's a problem.

**Comment by Levendo** [comment]
Hey, i had some time and i think i've found something.

When the total number of connected + disconnected peer count equals = 16382. Server no longer accepts a new connection. It does not matter when a client peer is connected and disconnected. they can be connected at some intervals. Messaging is working. 

How did i get it?
I wrote a batch command to simulate basic lobby functionality. That is connecting a new client between an interval(each 5 seconds) as a separate process. Each client process also sends messages in random time with random data, later client disconnects. (5 mins later) With using this setup, i made 2 tests; 

First test took like 12 hours when server stops to accept a new connection, message sending frequency was same as the second test. But client creation frequency was different. It was "create a client process for each 5 seconds and disconnect and die in 5 mins.".

Second test took like 7 hours when server stops to accept a new connection, message sending frequency was same as the first test. But client creation frequency was different, higher. It was "create a client process for each 2 seconds and die in 1 mins." (high client creation frequency)

I've logged when every client connects and disconnects and counted it. For each test this count number is equal to 16382 (which is half-short smt.) and these 2 tests were different. 

What i expected result would be not to have any limit on total connected/disconnected clients per very same game server.

I still have some time to discover it, and i'll let you know. Thank you.

**Comment by Levendo** [comment]
...Continues

Okay, i debug the below code. It is the exact time when a new, fresh client (new process) connecting to the server. (The server is already connected/disconnected 16382 times. contains 0 connections)

```
void CSharedSocket::CallbackRecvPacket( const void *pPkt, int cbPkt, const netadr_t &adrFrom, CSharedSocket *pSock )
{
	// Locate the client
	int idx = pSock->m_mapRemoteHosts.Find( adrFrom );	
        
// Select the callback to invoke, ether client-specific, or the default
	const CRecvPacketCallback &callback = ( idx == pSock->m_mapRemoteHosts.InvalidIndex() ) ? pSock->m_callbackDefault : pSock->m_mapRemoteHosts[ idx ]->m_callback;	
       
 // Execute the callback
	callback( pPkt, cbPkt, adrFrom );
}
```

The "idx" parameter is retrieved from map like structure "m_mapRemoteHosts" for the new connected client (i know it is retrieved because it is not -1) and calls the callback at the end. Just wondering is it okay for a new client connection is already included in "pSock->m_mapRemoteHosts" container? Well i dunno.

i continue to debug and i'm stuck below at the first if statement:

```
void CSteamNetworkConnectionUDP::Received_ChallengeOrConnectRequest( const char *pszDebugPacketType, uint32 unPacketConnectionID, SteamNetworkingMicroseconds usecNow )
{
	// If wrong connection ID, then check for sending a generic reply and bail
	if ( unPacketConnectionID != m_unConnectionIDRemote )
	{
		ReportBadPacketIPv4( pszDebugPacketType, "Incorrect connection ID, when we do have a connection for this address.  Could be spoofed, ignoring." );
		
// Let's not send a reply in this case
		//if ( BCheckGlobalSpamReplyRateLimit( usecNow ) )
		//	SendNoConnection( unPacketConnectionID );
		return;
	}

// ***** Some other codes here, no need to mention, because i'm unable to reach here. *****
}
```

"if ( unPacketConnectionID != m_unConnectionIDRemote )" statement success and "ReportBadPacketIPv4" and "return" is called. Wrong connection id.

So as a result a new client was unable to connect to the server. All felt like something is happening to server after too many connect/disconnects. (after 16382 times)

Test platform/env.: I run the client/s and server application on the very same PC using windows platform. My server and client applications are 2 projects in a single solution. I use VS 2019 and i'm building for .Net Core(able to run on Linux later) with using a proper binding class. I've built the GNS library with VS 2017, I use the native GNS library from .net core project. Well, everything works fluently except this connect/disconnect limitation. Tremendous library so far.

Any idea, help would be appreciated :) Thank you.

**Comment by fletcherdvalve** [comment]
Thanks for that very detailed bug report!

I'll look into this when I have a chance.  I think you definitely have something here.  And it's totally possible it's something we haven't hit in the wild in the existing use cases.

**Comment by Levendo** [comment]
Hey,

I want to share some more discovery that may help.

I continue to debug and i've discovered remote hosts (clients) information are saved at containers on connect; "pSock->m_mapRemoteHosts" , "g_mapConnections".

Even the connection between the client and server drops or problem occurs or client closes with disconnect, those maps still contains the related information, not removed.
When another client connects, if somehow new connected client connection internal port is already the port with the first connected client (which means container/s contains it), problem starts to arise. Client becomes unable to connect, because it stucks at assertion checks there.

So as a solution what i discovered the **FreeResources** interface exists at _CSteamNetworkConnectionBase_ class that free the resources, removes the connection information from those containers. 

So I called **FreeResources**(); on "Received_Data" method as below. (I actually called it after each "SendConnectionClosedOrNoConnection()" method on _CSteamNetworkConnectionUDP_ class, for simplicity showing the one below only)

```
void CSteamNetworkConnectionUDP::Received_Data( const uint8 *pPkt, int cbPkt, SteamNetworkingMicroseconds usecNow )
{

	if ( cbPkt < sizeof(UDPDataMsgHdr) )
	{
		ReportBadPacketIPv4( "DataPacket", "Packet of size %d is too small.", cbPkt );
		return;
	}

	// Check cookie
	const UDPDataMsgHdr *hdr = (const UDPDataMsgHdr *)pPkt;
	if ( LittleDWord( hdr->m_unToConnectionID ) != m_unConnectionIDLocal )
	{

		// Wrong session.  It could be an old session, or it could be spoofed.
		ReportBadPacketIPv4( "DataPacket", "Incorrect connection ID" );
		if ( BCheckGlobalSpamReplyRateLimit( usecNow ) )
		{
			SendNoConnection( LittleDWord( hdr->m_unToConnectionID ), 0 );
		}
		return;
	}
	uint16 nWirePktNumber = LittleWord( hdr->m_unSeqNum );

	// Check state
	switch ( GetState() )
	{
		case k_ESteamNetworkingConnectionState_Dead:
		case k_ESteamNetworkingConnectionState_None:
		case k_ESteamNetworkingConnectionState_FindingRoute: // not used for raw UDP
		default:
			Assert( false );
			return;

		case k_ESteamNetworkingConnectionState_ClosedByPeer:
		case k_ESteamNetworkingConnectionState_FinWait:
		case k_ESteamNetworkingConnectionState_ProblemDetectedLocally:
			SendConnectionClosedOrNoConnection();
                        // Free the resources that is no longer required for connected client
			FreeResources(); 
			return;
        .
        .
        . // Rest of the method
        .
        .
```

Well, It did the job for me, no longer connect/disconnect count limit. Debugged that; connections at containers removed when each client disconnects or drops and inserted when new one connects.

I tested it with 32000 client connected disconnected instead of 16382. Works smoothly.

Well, the reason i just wanted to share my discovery is to help somehow when you have the time to check, may speed up things, as long as i don't have the overall knowledge of the system, my perspective is limited, i'm not sure if freeing the resources there is really okay or i messed stuff :)

Hope that helps somehow. Thank you.

**Comment by fletcherdvalve** [comment]
I think I might know what's going on.  When a connection is closed by the peer, is your application ever cleaning up the connection by calling CloseConnection()?  You still need to close it locally to free up resources.  Same thing if it times out.  If your app doesn't respond to the connection state changed callback and close the connection, then yes, you will accumulate connections like this.

I probably could add code to have connections check back after several seconds of entering the "closed by peer" or "problem detected locally" states.  And if they still exist, then they could assert and warn you that you are not cleaning them up.

**Comment by Levendo** [comment]
Hmm i see, i didn't know i have to call it for ProblemDetectedLocally as well. Actually chat example calls it for both. C# side missing it on my end.

I've checked our server app. we call CloseConnection() on ConnectionState.ClosedByPeer: but not on ConnectionState.ProblemDetectedLocally. which does not free up the resources i guess. That's a problem :)

Yes, check back could be helpful. So thank you i think this is it. I will be testing tomorrow. Sorry to bother. Thanks.

**Comment by fletcherdvalve** [comment]
Try running with 7ff2400901c516367ba7c04d7418bafc413cddbe.  If you see that spew, then there's probably an application bug.  If not, then we have a bug in this library

**Comment by Levendo** [comment]
Ah Okay thanks. Good catch.

I tested and i see the spew which proves it is an application bug instead of library. 

We have started to develop our c# binding from the git reference, taking as a base: https://github.com/nxrighthere/ValveSockets-CSharp/tree/1.1.0
which unfortunately is not handling the case _ConnectionState.ProblemDetectedLocally_: on the example server application. So no "CloseConnection()" when _ProblemDetectedLocally_  occurs :/

Well, this means this issue does not belong here, better to be there. Thank you.

**Comment by fletcherdvalve** [comment]
Is it expected in your test case for so many connections to fail?  Are you explicitly simulating network failure to test it?  I might not understand your test situation fully, but that many failures seems like a lot.

**Comment by Levendo** [comment]
Problem is solved.

My test was simple, i have a batch command which creates a series of client processes per 1 second, running the exe. Each connects to the very same game server and and they disconnect after 3 seconds. I do it for 20000 clients, and no problem occurred. All is okay for now.

Problem was on the c# binding side of game server application, it is fixed [here](https://github.com/nxrighthere/ValveSockets-CSharp/issues/7).
The connection needs to be closed by "CloseConnection" on ProblemDetectedLocally state on server application, which we were missing. So the connections not cleared and become problematic later.

Think it like, you have a container which all the connections are saved. Later, failed or dropped connections are not removed from containers. Later a situation comes when a new client want to connect but the inner port of the the client is already in the container, Then failed to connect. This happens if you do not CloseConnection on ProblemDetectedLocally on server side.

Well, all is good. Thank you so much, took your valuable time.
